%% Generated by RAG ModelSpec pipeline
% task_goal: 
% model_id: arx_identification
% generator_strategy: template
function [y, f] = arx_identification(mode, time, Ts, x, u)
    INIT = 10102;  % 初始化模式
    CONT = 10103;  % 连续计算模式
    OUT  = 10111;  % 输出模式
    EXIT = 10106;  % 退出模式

    na = 2;
    nb = 2;
    nk = 1;
    a_demo = [1.2; -0.5];
    b_demo = [0.4; 0.2];

    state_dim = max(0, 4);
    output_dim = max(0, 1);
    input_dim = max(0, 1);

    if nargin < 4 || isempty(x)
        x = zeros(4, 1);
    else
        x = x(:);
    end
    if state_dim == 0
        x = zeros(0, 1);
    elseif numel(x) < state_dim
        x = [x; zeros(state_dim - numel(x), 1)];
    elseif numel(x) > state_dim
        x = x(1:state_dim);
    end

    if nargin < 5 || isempty(u)
        u = 0;
    else
        u = u(:);
    end
    if input_dim == 0
        u = zeros(0, 1);
    elseif numel(u) < input_dim
        u = [u; zeros(input_dim - numel(u), 1)];
    elseif numel(u) > input_dim
        u = u(1:input_dim);
    end

    switch mode
        case INIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            sample_time = max(Ts, 1);
            if sample_time <= 0
                sample_time = 1;
            end
            prev_y1 = x(1);
            prev_y2 = x(2);
            prev_u1 = x(3);
            prev_u2 = x(4);
            current_u = u(1);
            predicted_y = 0;
            if na >= 1
                predicted_y = predicted_y + a_demo(1) * prev_y1;
            end
            if na >= 2
                predicted_y = predicted_y + a_demo(2) * prev_y2;
            end
            if nb >= 1
                predicted_y = predicted_y + b_demo(1) * prev_u1;
            end
            if nb >= 2
                predicted_y = predicted_y + b_demo(2) * prev_u2;
            end
            next_state = [predicted_y; prev_y1; current_u; prev_u1];
            y(1) = predicted_y;
            f = (next_state - x) / sample_time;

        case CONT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            sample_time = max(Ts, 1);
            if sample_time <= 0
                sample_time = 1;
            end
            prev_y1 = x(1);
            prev_y2 = x(2);
            prev_u1 = x(3);
            prev_u2 = x(4);
            current_u = u(1);
            predicted_y = 0;
            if na >= 1
                predicted_y = predicted_y + a_demo(1) * prev_y1;
            end
            if na >= 2
                predicted_y = predicted_y + a_demo(2) * prev_y2;
            end
            if nb >= 1
                predicted_y = predicted_y + b_demo(1) * prev_u1;
            end
            if nb >= 2
                predicted_y = predicted_y + b_demo(2) * prev_u2;
            end
            next_state = [predicted_y; prev_y1; current_u; prev_u1];
            y(1) = predicted_y;
            f = (next_state - x) / sample_time;

        case OUT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            sample_time = max(Ts, 1);
            if sample_time <= 0
                sample_time = 1;
            end
            prev_y1 = x(1);
            prev_y2 = x(2);
            prev_u1 = x(3);
            prev_u2 = x(4);
            current_u = u(1);
            predicted_y = 0;
            if na >= 1
                predicted_y = predicted_y + a_demo(1) * prev_y1;
            end
            if na >= 2
                predicted_y = predicted_y + a_demo(2) * prev_y2;
            end
            if nb >= 1
                predicted_y = predicted_y + b_demo(1) * prev_u1;
            end
            if nb >= 2
                predicted_y = predicted_y + b_demo(2) * prev_u2;
            end
            next_state = [predicted_y; prev_y1; current_u; prev_u1];
            y(1) = predicted_y;

        case EXIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);

        otherwise
            error('Invalid mode');
    end
end