%% Generated by RAG ModelSpec pipeline
% task_goal: 
% model_id: battery_rc_model
% generator_strategy: template
function [y, f] = battery_rc_model(mode, time, Ts, x, u)
    INIT = 10102;  % 初始化模式
    CONT = 10103;  % 连续计算模式
    OUT  = 10111;  % 输出模式
    EXIT = 10106;  % 退出模式

    Q = 2.3 * 3600;
    R0 = 0.03;
    R1 = 0.015;
    C1 = 2400;

    state_dim = max(0, 2);
    output_dim = max(0, 2);
    input_dim = max(0, 1);

    if nargin < 4 || isempty(x)
        x = [1; 0];
    else
        x = x(:);
    end
    if state_dim == 0
        x = zeros(0, 1);
    elseif numel(x) < state_dim
        x = [x; zeros(state_dim - numel(x), 1)];
    elseif numel(x) > state_dim
        x = x(1:state_dim);
    end

    if nargin < 5 || isempty(u)
        u = 1.5;
    else
        u = u(:);
    end
    if input_dim == 0
        u = zeros(0, 1);
    elseif numel(u) < input_dim
        u = [u; zeros(input_dim - numel(u), 1)];
    elseif numel(u) > input_dim
        u = u(1:input_dim);
    end

    switch mode
        case INIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            soc = min(max(x(1), 0), 1);
            v1 = x(2);
            current = u(1);
            voc = 3.0 + 1.2 * soc - 0.1 * soc^2;
            terminal_voltage = voc - current * R0 - v1;
            y(1) = terminal_voltage;
            y(2) = soc;
            f(1) = -current / Q;
            f(2) = -(1 / (R1 * C1)) * v1 + current / C1;

        case CONT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            soc = min(max(x(1), 0), 1);
            v1 = x(2);
            current = u(1);
            voc = 3.0 + 1.2 * soc - 0.1 * soc^2;
            terminal_voltage = voc - current * R0 - v1;
            y(1) = terminal_voltage;
            y(2) = soc;
            f(1) = -current / Q;
            f(2) = -(1 / (R1 * C1)) * v1 + current / C1;

        case OUT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            soc = min(max(x(1), 0), 1);
            v1 = x(2);
            current = u(1);
            voc = 3.0 + 1.2 * soc - 0.1 * soc^2;
            terminal_voltage = voc - current * R0 - v1;
            y(1) = terminal_voltage;
            y(2) = soc;

        case EXIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);

        otherwise
            error('Invalid mode');
    end
end