%% Generated by RAG ModelSpec pipeline
% task_goal: 
% model_id: fft_lowpass_filter
% generator_strategy: template
function [y, f] = fft_lowpass_filter(mode, time, Ts, x, u)
    INIT = 10102;  % 初始化模式
    CONT = 10103;  % 连续计算模式
    OUT  = 10111;  % 输出模式
    EXIT = 10106;  % 退出模式

    fs = 1000;
    cutoff = 40;

    state_dim = max(0, 1);
    output_dim = max(0, 2);
    input_dim = max(0, 1);

    if nargin < 4 || isempty(x)
        x = 0;
    else
        x = x(:);
    end
    if state_dim == 0
        x = zeros(0, 1);
    elseif numel(x) < state_dim
        x = [x; zeros(state_dim - numel(x), 1)];
    elseif numel(x) > state_dim
        x = x(1:state_dim);
    end

    if nargin < 5 || isempty(u)
        u = sin(2 * pi * 5 * time) + 0.6 * sin(2 * pi * 80 * time);
    else
        u = u(:);
    end
    if input_dim == 0
        u = zeros(0, 1);
    elseif numel(u) < input_dim
        u = [u; zeros(input_dim - numel(u), 1)];
    elseif numel(u) > input_dim
        u = u(1:input_dim);
    end

    switch mode
        case INIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            sample_time = max(Ts, 1 / fs);
            if sample_time <= 0
                sample_time = 1 / fs;
            end
            signal_in = u(1);
            alpha = min(max(2 * pi * cutoff / fs, 0), 1);
            filtered = x(1) + alpha * (signal_in - x(1));
            y(1) = signal_in;
            y(2) = filtered;
            f(1) = (filtered - x(1)) / sample_time;

        case CONT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            sample_time = max(Ts, 1 / fs);
            if sample_time <= 0
                sample_time = 1 / fs;
            end
            signal_in = u(1);
            alpha = min(max(2 * pi * cutoff / fs, 0), 1);
            filtered = x(1) + alpha * (signal_in - x(1));
            y(1) = signal_in;
            y(2) = filtered;
            f(1) = (filtered - x(1)) / sample_time;

        case OUT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            sample_time = max(Ts, 1 / fs);
            if sample_time <= 0
                sample_time = 1 / fs;
            end
            signal_in = u(1);
            alpha = min(max(2 * pi * cutoff / fs, 0), 1);
            filtered = x(1) + alpha * (signal_in - x(1));
            y(1) = signal_in;
            y(2) = filtered;

        case EXIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);

        otherwise
            error('Invalid mode');
    end
end