%% Generated by RAG ModelSpec pipeline
% task_goal: 
% model_id: kalman_tracking
% generator_strategy: template
function [y, f] = kalman_tracking(mode, time, Ts, x, u)
    INIT = 10102;  % 初始化模式
    CONT = 10103;  % 连续计算模式
    OUT  = 10111;  % 输出模式
    EXIT = 10106;  % 退出模式

    dt = 0.1;
    process_noise = 0.01;
    measurement_noise = 0.1;

    state_dim = max(0, 4);
    output_dim = max(0, 3);
    input_dim = max(0, 1);

    if nargin < 4 || isempty(x)
        x = [0; 1; 0; 1];
    else
        x = x(:);
    end
    if state_dim == 0
        x = zeros(0, 1);
    elseif numel(x) < state_dim
        x = [x; zeros(state_dim - numel(x), 1)];
    elseif numel(x) > state_dim
        x = x(1:state_dim);
    end

    if nargin < 5 || isempty(u)
        u = x(1);
    else
        u = u(:);
    end
    if input_dim == 0
        u = zeros(0, 1);
    elseif numel(u) < input_dim
        u = [u; zeros(input_dim - numel(u), 1)];
    elseif numel(u) > input_dim
        u = u(1:input_dim);
    end

    switch mode
        case INIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            sample_time = max(Ts, dt);
            if sample_time <= 0
                sample_time = dt;
            end
            true_pos = x(1);
            true_vel = x(2);
            est_pos = x(3);
            est_vel = x(4);
            measurement = u(1);
            alpha = min(max(process_noise / max(process_noise + measurement_noise, 1e-6), 0.05), 0.95);
            beta = min(max(alpha / max(sample_time, 1e-6), 0.01), 2.0);
            pred_pos = est_pos + est_vel * sample_time;
            pred_vel = est_vel;
            innovation = measurement - pred_pos;
            next_est_pos = pred_pos + alpha * innovation;
            next_est_vel = pred_vel + beta * innovation;
            y(1) = measurement;
            y(2) = next_est_pos;
            y(3) = next_est_vel;
            f(1) = true_vel;
            f(2) = 0;
            f(3) = (next_est_pos - est_pos) / sample_time;
            f(4) = (next_est_vel - est_vel) / sample_time;

        case CONT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            sample_time = max(Ts, dt);
            if sample_time <= 0
                sample_time = dt;
            end
            true_pos = x(1);
            true_vel = x(2);
            est_pos = x(3);
            est_vel = x(4);
            measurement = u(1);
            alpha = min(max(process_noise / max(process_noise + measurement_noise, 1e-6), 0.05), 0.95);
            beta = min(max(alpha / max(sample_time, 1e-6), 0.01), 2.0);
            pred_pos = est_pos + est_vel * sample_time;
            pred_vel = est_vel;
            innovation = measurement - pred_pos;
            next_est_pos = pred_pos + alpha * innovation;
            next_est_vel = pred_vel + beta * innovation;
            y(1) = measurement;
            y(2) = next_est_pos;
            y(3) = next_est_vel;
            f(1) = true_vel;
            f(2) = 0;
            f(3) = (next_est_pos - est_pos) / sample_time;
            f(4) = (next_est_vel - est_vel) / sample_time;

        case OUT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            sample_time = max(Ts, dt);
            if sample_time <= 0
                sample_time = dt;
            end
            true_pos = x(1);
            true_vel = x(2);
            est_pos = x(3);
            est_vel = x(4);
            measurement = u(1);
            alpha = min(max(process_noise / max(process_noise + measurement_noise, 1e-6), 0.05), 0.95);
            beta = min(max(alpha / max(sample_time, 1e-6), 0.01), 2.0);
            pred_pos = est_pos + est_vel * sample_time;
            pred_vel = est_vel;
            innovation = measurement - pred_pos;
            next_est_pos = pred_pos + alpha * innovation;
            next_est_vel = pred_vel + beta * innovation;
            y(1) = measurement;
            y(2) = next_est_pos;
            y(3) = next_est_vel;

        case EXIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);

        otherwise
            error('Invalid mode');
    end
end