%% Generated by RAG ModelSpec pipeline
% task_goal: 
% model_id: lanchester_battle_attrition
% generator_strategy: template
function [y, f] = lanchester_battle_attrition(mode, time, Ts, x, u)
    INIT = 10102;  % 初始化模式
    CONT = 10103;  % 连续计算模式
    OUT  = 10111;  % 输出模式
    EXIT = 10106;  % 退出模式

    alpha = 0.035;
    beta = 0.04;

    state_dim = max(0, 2);
    output_dim = max(0, 2);
    input_dim = max(0, 0);

    if nargin < 4 || isempty(x)
        x = [120.0; 100.0];
    else
        x = x(:);
    end
    if state_dim == 0
        x = zeros(0, 1);
    elseif numel(x) < state_dim
        x = [x; zeros(state_dim - numel(x), 1)];
    elseif numel(x) > state_dim
        x = x(1:state_dim);
    end

    if nargin < 5 || isempty(u)
        u = zeros(0, 1);
    else
        u = u(:);
    end
    if input_dim == 0
        u = zeros(0, 1);
    elseif numel(u) < input_dim
        u = [u; zeros(input_dim - numel(u), 1)];
    elseif numel(u) > input_dim
        u = u(1:input_dim);
    end

    switch mode
        case INIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            red_force = max(x(1), 0);
            blue_force = max(x(2), 0);
            red_dot = -alpha * blue_force;
            blue_dot = -beta * red_force;
            if red_force <= 0 || blue_force <= 0
                red_dot = 0;
                blue_dot = 0;
            end
            y(1) = red_force;
            y(2) = blue_force;
            f(1) = red_dot;
            f(2) = blue_dot;

        case CONT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            red_force = max(x(1), 0);
            blue_force = max(x(2), 0);
            red_dot = -alpha * blue_force;
            blue_dot = -beta * red_force;
            if red_force <= 0 || blue_force <= 0
                red_dot = 0;
                blue_dot = 0;
            end
            y(1) = red_force;
            y(2) = blue_force;
            f(1) = red_dot;
            f(2) = blue_dot;

        case OUT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            red_force = max(x(1), 0);
            blue_force = max(x(2), 0);
            red_dot = -alpha * blue_force;
            blue_dot = -beta * red_force;
            if red_force <= 0 || blue_force <= 0
                red_dot = 0;
                blue_dot = 0;
            end
            y(1) = red_force;
            y(2) = blue_force;

        case EXIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);

        otherwise
            error('Invalid mode');
    end
end