%% Generated by RAG ModelSpec pipeline
% task_goal: 
% model_id: mass_spring_damper_ode
% generator_strategy: template
function [y, f] = mass_spring_damper_ode(mode, time, Ts, x, u)
    INIT = 10102;  % 初始化模式
    CONT = 10103;  % 连续计算模式
    OUT  = 10111;  % 输出模式
    EXIT = 10106;  % 退出模式

    m = 1.0;
    c = 0.5;
    k = 20.0;

    state_dim = max(0, 2);
    output_dim = max(0, 2);
    input_dim = max(0, 1);

    if nargin < 4 || isempty(x)
        x = [0; 0];
    else
        x = x(:);
    end
    if state_dim == 0
        x = zeros(0, 1);
    elseif numel(x) < state_dim
        x = [x; zeros(state_dim - numel(x), 1)];
    elseif numel(x) > state_dim
        x = x(1:state_dim);
    end

    if nargin < 5 || isempty(u)
        u = 0;
    else
        u = u(:);
    end
    if input_dim == 0
        u = zeros(0, 1);
    elseif numel(u) < input_dim
        u = [u; zeros(input_dim - numel(u), 1)];
    elseif numel(u) > input_dim
        u = u(1:input_dim);
    end

    switch mode
        case INIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            position = x(1);
            velocity = x(2);
            force = u(1);
            y(1) = position;
            y(2) = velocity;
            f(1) = velocity;
            f(2) = (force - c * velocity - k * position) / m;

        case CONT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            position = x(1);
            velocity = x(2);
            force = u(1);
            y(1) = position;
            y(2) = velocity;
            f(1) = velocity;
            f(2) = (force - c * velocity - k * position) / m;

        case OUT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            position = x(1);
            velocity = x(2);
            force = u(1);
            y(1) = position;
            y(2) = velocity;

        case EXIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);

        otherwise
            error('Invalid mode');
    end
end