%% Generated by RAG ModelSpec pipeline
% task_goal: 
% model_id: missile_flight_2d
% generator_strategy: template
function [y, f] = missile_flight_2d(mode, time, Ts, x, u)
    INIT = 10102;  % 初始化模式
    CONT = 10103;  % 连续计算模式
    OUT  = 10111;  % 输出模式
    EXIT = 10106;  % 退出模式

    mass0 = 120.0;
    thrust_default = 6000.0;
    Cd = 0.32;
    A = 0.08;
    rho = 1.225;
    g = 9.81;
    burn_time = 8.0;

    state_dim = max(0, 4);
    output_dim = max(0, 3);
    input_dim = max(0, 2);

    if nargin < 4 || isempty(x)
        x = [0; 0; 30.0 * cos(0.7853981633974483); 30.0 * sin(0.7853981633974483)];
    else
        x = x(:);
    end
    if state_dim == 0
        x = zeros(0, 1);
    elseif numel(x) < state_dim
        x = [x; zeros(state_dim - numel(x), 1)];
    elseif numel(x) > state_dim
        x = x(1:state_dim);
    end

    if nargin < 5 || isempty(u)
        u = [thrust_default; 45.0];
    else
        u = u(:);
    end
    if input_dim == 0
        u = zeros(0, 1);
    elseif numel(u) < input_dim
        u = [u; zeros(input_dim - numel(u), 1)];
    elseif numel(u) > input_dim
        u = u(1:input_dim);
    end

    switch mode
        case INIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            pos_x = x(1);
            pos_y = max(x(2), 0);
            vel_x = x(3);
            vel_y = x(4);
            thrust_val = max(u(1), 0);
            launch_angle_deg = max(min(u(2), 90), -10);
            theta = launch_angle_deg * pi / 180;
            if time > burn_time
                thrust_val = 0;
            end
            speed = hypot(vel_x, vel_y);
            if speed > 1e-8
                drag = 0.5 * rho * Cd * A * speed^2;
                drag_x = drag * vel_x / speed;
                drag_y = drag * vel_y / speed;
            else
                drag_x = 0;
                drag_y = 0;
            end
            ax_val = (thrust_val * cos(theta) - drag_x) / mass0;
            ay_val = (thrust_val * sin(theta) - drag_y) / mass0 - g;
            if pos_y <= 0 && vel_y < 0 && time > 0
                ay_val = 0;
                vel_y = 0;
            end
            y(1) = pos_x;
            y(2) = pos_y;
            y(3) = speed;
            f(1) = vel_x;
            f(2) = vel_y;
            f(3) = ax_val;
            f(4) = ay_val;

        case CONT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            pos_x = x(1);
            pos_y = max(x(2), 0);
            vel_x = x(3);
            vel_y = x(4);
            thrust_val = max(u(1), 0);
            launch_angle_deg = max(min(u(2), 90), -10);
            theta = launch_angle_deg * pi / 180;
            if time > burn_time
                thrust_val = 0;
            end
            speed = hypot(vel_x, vel_y);
            if speed > 1e-8
                drag = 0.5 * rho * Cd * A * speed^2;
                drag_x = drag * vel_x / speed;
                drag_y = drag * vel_y / speed;
            else
                drag_x = 0;
                drag_y = 0;
            end
            ax_val = (thrust_val * cos(theta) - drag_x) / mass0;
            ay_val = (thrust_val * sin(theta) - drag_y) / mass0 - g;
            if pos_y <= 0 && vel_y < 0 && time > 0
                ay_val = 0;
                vel_y = 0;
            end
            y(1) = pos_x;
            y(2) = pos_y;
            y(3) = speed;
            f(1) = vel_x;
            f(2) = vel_y;
            f(3) = ax_val;
            f(4) = ay_val;

        case OUT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            pos_x = x(1);
            pos_y = max(x(2), 0);
            vel_x = x(3);
            vel_y = x(4);
            thrust_val = max(u(1), 0);
            launch_angle_deg = max(min(u(2), 90), -10);
            theta = launch_angle_deg * pi / 180;
            if time > burn_time
                thrust_val = 0;
            end
            speed = hypot(vel_x, vel_y);
            if speed > 1e-8
                drag = 0.5 * rho * Cd * A * speed^2;
                drag_x = drag * vel_x / speed;
                drag_y = drag * vel_y / speed;
            else
                drag_x = 0;
                drag_y = 0;
            end
            ax_val = (thrust_val * cos(theta) - drag_x) / mass0;
            ay_val = (thrust_val * sin(theta) - drag_y) / mass0 - g;
            if pos_y <= 0 && vel_y < 0 && time > 0
                ay_val = 0;
                vel_y = 0;
            end
            y(1) = pos_x;
            y(2) = pos_y;
            y(3) = speed;

        case EXIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);

        otherwise
            error('Invalid mode');
    end
end