%% Generated by RAG ModelSpec pipeline
% task_goal: 
% model_id: mpc_control
% generator_strategy: template
function [y, f] = mpc_control(mode, time, Ts, x, u)
    INIT = 10102;  % 初始化模式
    CONT = 10103;  % 连续计算模式
    OUT  = 10111;  % 输出模式
    EXIT = 10106;  % 退出模式

    Ts_default = 0.1;
    prediction_horizon = 20;
    control_horizon = 5;
    [A, B, C, D] = tf2ss([1], [1 1 0]);
    plant_state_dim = size(A, 1);

    state_dim = max(0, plant_state_dim + 1);
    output_dim = max(0, 2);
    input_dim = max(0, 1);

    if nargin < 4 || isempty(x)
        x = zeros(state_dim, 1);
    else
        x = x(:);
    end
    if state_dim == 0
        x = zeros(0, 1);
    elseif numel(x) < state_dim
        x = [x; zeros(state_dim - numel(x), 1)];
    elseif numel(x) > state_dim
        x = x(1:state_dim);
    end

    if nargin < 5 || isempty(u)
        u = 1;
    else
        u = u(:);
    end
    if input_dim == 0
        u = zeros(0, 1);
    elseif numel(u) < input_dim
        u = [u; zeros(input_dim - numel(u), 1)];
    elseif numel(u) > input_dim
        u = u(1:input_dim);
    end

    switch mode
        case INIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            plant_state = x(1:plant_state_dim);
            last_u = x(plant_state_dim + 1);
            sample_time = max(Ts, Ts_default);
            if sample_time <= 0
                sample_time = Ts_default;
            end
            reference = u(1);
            pred_output = C * plant_state + D * last_u;
            pred_output = pred_output(:);
            error_val = reference - pred_output(1);
            plant_rate = 0;
            if plant_state_dim >= 2
                plant_rate = plant_state(2);
            end
            horizon_gain = max(prediction_horizon, 1) / max(control_horizon, 1);
            control_val = horizon_gain * 0.05 * error_val - 0.1 * plant_rate;
            control_val = min(max(control_val, -1), 1);
            plant_output = C * plant_state + D * control_val;
            plant_output = plant_output(:);
            y(1) = plant_output(1);
            y(2) = control_val;
            f(1:plant_state_dim) = A * plant_state + B * control_val;
            f(plant_state_dim + 1) = (control_val - last_u) / sample_time;

        case CONT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            plant_state = x(1:plant_state_dim);
            last_u = x(plant_state_dim + 1);
            sample_time = max(Ts, Ts_default);
            if sample_time <= 0
                sample_time = Ts_default;
            end
            reference = u(1);
            pred_output = C * plant_state + D * last_u;
            pred_output = pred_output(:);
            error_val = reference - pred_output(1);
            plant_rate = 0;
            if plant_state_dim >= 2
                plant_rate = plant_state(2);
            end
            horizon_gain = max(prediction_horizon, 1) / max(control_horizon, 1);
            control_val = horizon_gain * 0.05 * error_val - 0.1 * plant_rate;
            control_val = min(max(control_val, -1), 1);
            plant_output = C * plant_state + D * control_val;
            plant_output = plant_output(:);
            y(1) = plant_output(1);
            y(2) = control_val;
            f(1:plant_state_dim) = A * plant_state + B * control_val;
            f(plant_state_dim + 1) = (control_val - last_u) / sample_time;

        case OUT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            plant_state = x(1:plant_state_dim);
            last_u = x(plant_state_dim + 1);
            sample_time = max(Ts, Ts_default);
            if sample_time <= 0
                sample_time = Ts_default;
            end
            reference = u(1);
            pred_output = C * plant_state + D * last_u;
            pred_output = pred_output(:);
            error_val = reference - pred_output(1);
            plant_rate = 0;
            if plant_state_dim >= 2
                plant_rate = plant_state(2);
            end
            horizon_gain = max(prediction_horizon, 1) / max(control_horizon, 1);
            control_val = horizon_gain * 0.05 * error_val - 0.1 * plant_rate;
            control_val = min(max(control_val, -1), 1);
            plant_output = C * plant_state + D * control_val;
            plant_output = plant_output(:);
            y(1) = plant_output(1);
            y(2) = control_val;

        case EXIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);

        otherwise
            error('Invalid mode');
    end
end