%% Generated by RAG ModelSpec pipeline
% task_goal: 
% model_id: pid_simulink_loop
% generator_strategy: template
function [y, f] = pid_simulink_loop(mode, time, Ts, x, u)
    INIT = 10102;  % 初始化模式
    CONT = 10103;  % 连续计算模式
    OUT  = 10111;  % 输出模式
    EXIT = 10106;  % 退出模式

    kp = 1.2;
    ki = 0.8;
    kd = 0.02;
    num = [1];
    den = [0.5 1];
    [A, B, C, D] = tf2ss(num, den);
    plant_state_dim = size(A, 1);

    state_dim = max(0, plant_state_dim + 2);
    output_dim = max(0, 2);
    input_dim = max(0, 1);

    if nargin < 4 || isempty(x)
        x = zeros(state_dim, 1);
    else
        x = x(:);
    end
    if state_dim == 0
        x = zeros(0, 1);
    elseif numel(x) < state_dim
        x = [x; zeros(state_dim - numel(x), 1)];
    elseif numel(x) > state_dim
        x = x(1:state_dim);
    end

    if nargin < 5 || isempty(u)
        u = 1;
    else
        u = u(:);
    end
    if input_dim == 0
        u = zeros(0, 1);
    elseif numel(u) < input_dim
        u = [u; zeros(input_dim - numel(u), 1)];
    elseif numel(u) > input_dim
        u = u(1:input_dim);
    end

    switch mode
        case INIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            plant_state = x(1:plant_state_dim);
            int_error = x(plant_state_dim + 1);
            prev_error = x(plant_state_dim + 2);
            reference = u(1);
            sample_time = max(Ts, 1e-6);
            open_loop_output = C * plant_state;
            open_loop_output = open_loop_output(:);
            error_val = reference - open_loop_output(1);
            error_dot = (error_val - prev_error) / sample_time;
            control_val = kp * error_val + ki * int_error + kd * error_dot;
            plant_output = C * plant_state + D * control_val;
            plant_output = plant_output(:);
            y(1) = plant_output(1);
            y(2) = control_val;
            f(1:plant_state_dim) = A * plant_state + B * control_val;
            f(plant_state_dim + 1) = error_val;
            f(plant_state_dim + 2) = error_dot;

        case CONT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            plant_state = x(1:plant_state_dim);
            int_error = x(plant_state_dim + 1);
            prev_error = x(plant_state_dim + 2);
            reference = u(1);
            sample_time = max(Ts, 1e-6);
            open_loop_output = C * plant_state;
            open_loop_output = open_loop_output(:);
            error_val = reference - open_loop_output(1);
            error_dot = (error_val - prev_error) / sample_time;
            control_val = kp * error_val + ki * int_error + kd * error_dot;
            plant_output = C * plant_state + D * control_val;
            plant_output = plant_output(:);
            y(1) = plant_output(1);
            y(2) = control_val;
            f(1:plant_state_dim) = A * plant_state + B * control_val;
            f(plant_state_dim + 1) = error_val;
            f(plant_state_dim + 2) = error_dot;

        case OUT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            plant_state = x(1:plant_state_dim);
            int_error = x(plant_state_dim + 1);
            prev_error = x(plant_state_dim + 2);
            reference = u(1);
            sample_time = max(Ts, 1e-6);
            open_loop_output = C * plant_state;
            open_loop_output = open_loop_output(:);
            error_val = reference - open_loop_output(1);
            error_dot = (error_val - prev_error) / sample_time;
            control_val = kp * error_val + ki * int_error + kd * error_dot;
            plant_output = C * plant_state + D * control_val;
            plant_output = plant_output(:);
            y(1) = plant_output(1);
            y(2) = control_val;

        case EXIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);

        otherwise
            error('Invalid mode');
    end
end