%% Generated by RAG ModelSpec pipeline
% task_goal: 
% model_id: pv_iv_curve
% generator_strategy: template
function [y, f] = pv_iv_curve(mode, time, Ts, x, u)
    INIT = 10102;  % 初始化模式
    CONT = 10103;  % 连续计算模式
    OUT  = 10111;  % 输出模式
    EXIT = 10106;  % 退出模式

    Isc = 8.2;
    Voc = 37.5;

    state_dim = max(0, 1);
    output_dim = max(0, 2);
    input_dim = max(0, 1);

    if nargin < 4 || isempty(x)
        x = 18.75;
    else
        x = x(:);
    end
    if state_dim == 0
        x = zeros(0, 1);
    elseif numel(x) < state_dim
        x = [x; zeros(state_dim - numel(x), 1)];
    elseif numel(x) > state_dim
        x = x(1:state_dim);
    end

    if nargin < 5 || isempty(u)
        u = 18.75;
    else
        u = u(:);
    end
    if input_dim == 0
        u = zeros(0, 1);
    elseif numel(u) < input_dim
        u = [u; zeros(input_dim - numel(u), 1)];
    elseif numel(u) > input_dim
        u = u(1:input_dim);
    end

    switch mode
        case INIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            voltage = max(min(u(1), Voc), 0);
            current = Isc * (1 - (voltage / max(Voc, 1e-6))^1.25);
            current = max(current, 0);
            power_val = voltage * current;
            y(1) = current;
            y(2) = power_val;
            f(1) = 0;

        case CONT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            voltage = max(min(u(1), Voc), 0);
            current = Isc * (1 - (voltage / max(Voc, 1e-6))^1.25);
            current = max(current, 0);
            power_val = voltage * current;
            y(1) = current;
            y(2) = power_val;
            f(1) = 0;

        case OUT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            voltage = max(min(u(1), Voc), 0);
            current = Isc * (1 - (voltage / max(Voc, 1e-6))^1.25);
            current = max(current, 0);
            power_val = voltage * current;
            y(1) = current;
            y(2) = power_val;

        case EXIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);

        otherwise
            error('Invalid mode');
    end
end