%% Generated by RAG ModelSpec pipeline
% task_goal: 
% model_id: radar_target_tracking_2d
% generator_strategy: template
function [y, f] = radar_target_tracking_2d(mode, time, Ts, x, u)
    INIT = 10102;  % 初始化模式
    CONT = 10103;  % 连续计算模式
    OUT  = 10111;  % 输出模式
    EXIT = 10106;  % 退出模式

    dt = 1.0;
    process_noise = 0.05;
    measurement_noise = 20.0;

    state_dim = max(0, 4);
    output_dim = max(0, 4);
    input_dim = max(0, 2);

    if nargin < 4 || isempty(x)
        x = [0.0; 0.0; 220.0; 40.0];
    else
        x = x(:);
    end
    if state_dim == 0
        x = zeros(0, 1);
    elseif numel(x) < state_dim
        x = [x; zeros(state_dim - numel(x), 1)];
    elseif numel(x) > state_dim
        x = x(1:state_dim);
    end

    if nargin < 5 || isempty(u)
        u = [0.0; 0.0];
    else
        u = u(:);
    end
    if input_dim == 0
        u = zeros(0, 1);
    elseif numel(u) < input_dim
        u = [u; zeros(input_dim - numel(u), 1)];
    elseif numel(u) > input_dim
        u = u(1:input_dim);
    end

    switch mode
        case INIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            sample_time = max(Ts, dt);
            if sample_time <= 0
                sample_time = dt;
            end
            est_x = x(1);
            est_y = x(2);
            est_vx = x(3);
            est_vy = x(4);
            meas_x = u(1);
            meas_y = u(2);
            alpha = min(max(process_noise / max(process_noise + measurement_noise, 1e-6), 0.05), 0.95);
            beta = min(max(alpha / max(sample_time, 1e-6), 0.01), 2.0);
            pred_x = est_x + est_vx * sample_time;
            pred_y = est_y + est_vy * sample_time;
            innovation_x = meas_x - pred_x;
            innovation_y = meas_y - pred_y;
            next_x = pred_x + alpha * innovation_x;
            next_y = pred_y + alpha * innovation_y;
            next_vx = est_vx + beta * innovation_x;
            next_vy = est_vy + beta * innovation_y;
            next_state = [next_x; next_y; next_vx; next_vy];
            y(1) = meas_x;
            y(2) = meas_y;
            y(3) = next_x;
            y(4) = next_y;
            f = (next_state - x) / sample_time;

        case CONT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            sample_time = max(Ts, dt);
            if sample_time <= 0
                sample_time = dt;
            end
            est_x = x(1);
            est_y = x(2);
            est_vx = x(3);
            est_vy = x(4);
            meas_x = u(1);
            meas_y = u(2);
            alpha = min(max(process_noise / max(process_noise + measurement_noise, 1e-6), 0.05), 0.95);
            beta = min(max(alpha / max(sample_time, 1e-6), 0.01), 2.0);
            pred_x = est_x + est_vx * sample_time;
            pred_y = est_y + est_vy * sample_time;
            innovation_x = meas_x - pred_x;
            innovation_y = meas_y - pred_y;
            next_x = pred_x + alpha * innovation_x;
            next_y = pred_y + alpha * innovation_y;
            next_vx = est_vx + beta * innovation_x;
            next_vy = est_vy + beta * innovation_y;
            next_state = [next_x; next_y; next_vx; next_vy];
            y(1) = meas_x;
            y(2) = meas_y;
            y(3) = next_x;
            y(4) = next_y;
            f = (next_state - x) / sample_time;

        case OUT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            sample_time = max(Ts, dt);
            if sample_time <= 0
                sample_time = dt;
            end
            est_x = x(1);
            est_y = x(2);
            est_vx = x(3);
            est_vy = x(4);
            meas_x = u(1);
            meas_y = u(2);
            alpha = min(max(process_noise / max(process_noise + measurement_noise, 1e-6), 0.05), 0.95);
            beta = min(max(alpha / max(sample_time, 1e-6), 0.01), 2.0);
            pred_x = est_x + est_vx * sample_time;
            pred_y = est_y + est_vy * sample_time;
            innovation_x = meas_x - pred_x;
            innovation_y = meas_y - pred_y;
            next_x = pred_x + alpha * innovation_x;
            next_y = pred_y + alpha * innovation_y;
            next_vx = est_vx + beta * innovation_x;
            next_vy = est_vy + beta * innovation_y;
            next_state = [next_x; next_y; next_vx; next_vy];
            y(1) = meas_x;
            y(2) = meas_y;
            y(3) = next_x;
            y(4) = next_y;

        case EXIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);

        otherwise
            error('Invalid mode');
    end
end