%% Generated by RAG ModelSpec pipeline
% task_goal: 
% model_id: robot_2dof_kinematics
% generator_strategy: template
function [y, f] = robot_2dof_kinematics(mode, time, Ts, x, u)
    INIT = 10102;  % 初始化模式
    CONT = 10103;  % 连续计算模式
    OUT  = 10111;  % 输出模式
    EXIT = 10106;  % 退出模式

    l1 = 0.6;
    l2 = 0.4;

    state_dim = max(0, 2);
    output_dim = max(0, 4);
    input_dim = max(0, 2);

    if nargin < 4 || isempty(x)
        x = [0; 0];
    else
        x = x(:);
    end
    if state_dim == 0
        x = zeros(0, 1);
    elseif numel(x) < state_dim
        x = [x; zeros(state_dim - numel(x), 1)];
    elseif numel(x) > state_dim
        x = x(1:state_dim);
    end

    if nargin < 5 || isempty(u)
        u = [0.7; 0.2];
    else
        u = u(:);
    end
    if input_dim == 0
        u = zeros(0, 1);
    elseif numel(u) < input_dim
        u = [u; zeros(input_dim - numel(u), 1)];
    elseif numel(u) > input_dim
        u = u(1:input_dim);
    end

    switch mode
        case INIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            sample_time = max(Ts, 1e-3);
            target_x = u(1);
            target_y = u(2);
            c2 = (target_x^2 + target_y^2 - l1^2 - l2^2) / (2 * l1 * l2);
            c2 = max(min(c2, 1), -1);
            s2 = -sqrt(max(0, 1 - c2^2));
            theta2_cmd = atan2(s2, c2);
            theta1_cmd = atan2(target_y, target_x) - atan2(l2 * sin(theta2_cmd), l1 + l2 * cos(theta2_cmd));
            fk_x = l1 * cos(theta1_cmd) + l2 * cos(theta1_cmd + theta2_cmd);
            fk_y = l1 * sin(theta1_cmd) + l2 * sin(theta1_cmd + theta2_cmd);
            next_state = [theta1_cmd; theta2_cmd];
            y(1) = theta1_cmd;
            y(2) = theta2_cmd;
            y(3) = fk_x;
            y(4) = fk_y;
            f = (next_state - x) / sample_time;

        case CONT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            sample_time = max(Ts, 1e-3);
            target_x = u(1);
            target_y = u(2);
            c2 = (target_x^2 + target_y^2 - l1^2 - l2^2) / (2 * l1 * l2);
            c2 = max(min(c2, 1), -1);
            s2 = -sqrt(max(0, 1 - c2^2));
            theta2_cmd = atan2(s2, c2);
            theta1_cmd = atan2(target_y, target_x) - atan2(l2 * sin(theta2_cmd), l1 + l2 * cos(theta2_cmd));
            fk_x = l1 * cos(theta1_cmd) + l2 * cos(theta1_cmd + theta2_cmd);
            fk_y = l1 * sin(theta1_cmd) + l2 * sin(theta1_cmd + theta2_cmd);
            next_state = [theta1_cmd; theta2_cmd];
            y(1) = theta1_cmd;
            y(2) = theta2_cmd;
            y(3) = fk_x;
            y(4) = fk_y;
            f = (next_state - x) / sample_time;

        case OUT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            sample_time = max(Ts, 1e-3);
            target_x = u(1);
            target_y = u(2);
            c2 = (target_x^2 + target_y^2 - l1^2 - l2^2) / (2 * l1 * l2);
            c2 = max(min(c2, 1), -1);
            s2 = -sqrt(max(0, 1 - c2^2));
            theta2_cmd = atan2(s2, c2);
            theta1_cmd = atan2(target_y, target_x) - atan2(l2 * sin(theta2_cmd), l1 + l2 * cos(theta2_cmd));
            fk_x = l1 * cos(theta1_cmd) + l2 * cos(theta1_cmd + theta2_cmd);
            fk_y = l1 * sin(theta1_cmd) + l2 * sin(theta1_cmd + theta2_cmd);
            next_state = [theta1_cmd; theta2_cmd];
            y(1) = theta1_cmd;
            y(2) = theta2_cmd;
            y(3) = fk_x;
            y(4) = fk_y;

        case EXIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);

        otherwise
            error('Invalid mode');
    end
end