%% Generated by RAG ModelSpec pipeline
% task_goal: 
% model_id: satellite_orbit_2body
% generator_strategy: template
function [y, f] = satellite_orbit_2body(mode, time, Ts, x, u)
    INIT = 10102;  % 初始化模式
    CONT = 10103;  % 连续计算模式
    OUT  = 10111;  % 输出模式
    EXIT = 10106;  % 退出模式

    mu = 398600000000000.0;
    Re = 6371000.0;

    state_dim = max(0, 4);
    output_dim = max(0, 3);
    input_dim = max(0, 0);

    if nargin < 4 || isempty(x)
        x = [6371000.0 + 400000.0; 0; 0; 7670.0];
    else
        x = x(:);
    end
    if state_dim == 0
        x = zeros(0, 1);
    elseif numel(x) < state_dim
        x = [x; zeros(state_dim - numel(x), 1)];
    elseif numel(x) > state_dim
        x = x(1:state_dim);
    end

    if nargin < 5 || isempty(u)
        u = zeros(0, 1);
    else
        u = u(:);
    end
    if input_dim == 0
        u = zeros(0, 1);
    elseif numel(u) < input_dim
        u = [u; zeros(input_dim - numel(u), 1)];
    elseif numel(u) > input_dim
        u = u(1:input_dim);
    end

    switch mode
        case INIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            pos_x = x(1);
            pos_y = x(2);
            vel_x = x(3);
            vel_y = x(4);
            radius = max(hypot(pos_x, pos_y), Re);
            ax_val = -mu * pos_x / radius^3;
            ay_val = -mu * pos_y / radius^3;
            altitude = radius - Re;
            speed = hypot(vel_x, vel_y);
            y(1) = pos_x;
            y(2) = pos_y;
            y(3) = altitude;
            f(1) = vel_x;
            f(2) = vel_y;
            f(3) = ax_val;
            f(4) = ay_val;

        case CONT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            pos_x = x(1);
            pos_y = x(2);
            vel_x = x(3);
            vel_y = x(4);
            radius = max(hypot(pos_x, pos_y), Re);
            ax_val = -mu * pos_x / radius^3;
            ay_val = -mu * pos_y / radius^3;
            altitude = radius - Re;
            speed = hypot(vel_x, vel_y);
            y(1) = pos_x;
            y(2) = pos_y;
            y(3) = altitude;
            f(1) = vel_x;
            f(2) = vel_y;
            f(3) = ax_val;
            f(4) = ay_val;

        case OUT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            pos_x = x(1);
            pos_y = x(2);
            vel_x = x(3);
            vel_y = x(4);
            radius = max(hypot(pos_x, pos_y), Re);
            ax_val = -mu * pos_x / radius^3;
            ay_val = -mu * pos_y / radius^3;
            altitude = radius - Re;
            speed = hypot(vel_x, vel_y);
            y(1) = pos_x;
            y(2) = pos_y;
            y(3) = altitude;

        case EXIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);

        otherwise
            error('Invalid mode');
    end
end