%% Generated by RAG ModelSpec pipeline
% task_goal: 
% model_id: state_space_response
% generator_strategy: template
function [y, f] = state_space_response(mode, time, Ts, x, u)
    INIT = 10102;  % 初始化模式
    CONT = 10103;  % 连续计算模式
    OUT  = 10111;  % 输出模式
    EXIT = 10106;  % 退出模式

    A = [0 1; -2 -3];
    B = [0; 1];
    C = [1 0];
    D = 0;

    state_dim = max(0, size(A, 1));
    output_dim = max(0, size(C, 1));
    input_dim = max(0, size(B, 2));

    if nargin < 4 || isempty(x)
        x = zeros(state_dim, 1);
    else
        x = x(:);
    end
    if state_dim == 0
        x = zeros(0, 1);
    elseif numel(x) < state_dim
        x = [x; zeros(state_dim - numel(x), 1)];
    elseif numel(x) > state_dim
        x = x(1:state_dim);
    end

    if nargin < 5 || isempty(u)
        u = ones(input_dim, 1);
    else
        u = u(:);
    end
    if input_dim == 0
        u = zeros(0, 1);
    elseif numel(u) < input_dim
        u = [u; zeros(input_dim - numel(u), 1)];
    elseif numel(u) > input_dim
        u = u(1:input_dim);
    end

    switch mode
        case INIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            response = C * x + D * u;
            response = response(:);
            y = response;
            f = A * x + B * u;

        case CONT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            response = C * x + D * u;
            response = response(:);
            y = response;
            f = A * x + B * u;

        case OUT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            response = C * x + D * u;
            response = response(:);
            y = response;

        case EXIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);

        otherwise
            error('Invalid mode');
    end
end