%% Generated by RAG ModelSpec pipeline
% task_goal: 
% model_id: torpedo_underwater_launch_1d
% generator_strategy: template
function [y, f] = torpedo_underwater_launch_1d(mode, time, Ts, x, u)
    INIT = 10102;  % 初始化模式
    CONT = 10103;  % 连续计算模式
    OUT  = 10111;  % 输出模式
    EXIT = 10106;  % 退出模式

    mass = 180.0;
    thrust_default = 3200.0;
    Cd = 0.35;
    A = 0.045;
    rho = 1000.0;
    Vd = 0.16;
    g = 9.81;

    state_dim = max(0, 2);
    output_dim = max(0, 2);
    input_dim = max(0, 1);

    if nargin < 4 || isempty(x)
        x = [0; 0];
    else
        x = x(:);
    end
    if state_dim == 0
        x = zeros(0, 1);
    elseif numel(x) < state_dim
        x = [x; zeros(state_dim - numel(x), 1)];
    elseif numel(x) > state_dim
        x = x(1:state_dim);
    end

    if nargin < 5 || isempty(u)
        u = thrust_default;
    else
        u = u(:);
    end
    if input_dim == 0
        u = zeros(0, 1);
    elseif numel(u) < input_dim
        u = [u; zeros(input_dim - numel(u), 1)];
    elseif numel(u) > input_dim
        u = u(1:input_dim);
    end

    switch mode
        case INIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            displacement = max(x(1), 0);
            velocity = x(2);
            thrust_val = u(1);
            weight = mass * g;
            buoyancy = rho * g * Vd;
            drag = 0.5 * rho * Cd * A * velocity * abs(velocity);
            accel = (thrust_val + buoyancy - weight - drag) / mass;
            y(1) = displacement;
            y(2) = velocity;
            f(1) = velocity;
            f(2) = accel;

        case CONT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            displacement = max(x(1), 0);
            velocity = x(2);
            thrust_val = u(1);
            weight = mass * g;
            buoyancy = rho * g * Vd;
            drag = 0.5 * rho * Cd * A * velocity * abs(velocity);
            accel = (thrust_val + buoyancy - weight - drag) / mass;
            y(1) = displacement;
            y(2) = velocity;
            f(1) = velocity;
            f(2) = accel;

        case OUT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            displacement = max(x(1), 0);
            velocity = x(2);
            thrust_val = u(1);
            weight = mass * g;
            buoyancy = rho * g * Vd;
            drag = 0.5 * rho * Cd * A * velocity * abs(velocity);
            accel = (thrust_val + buoyancy - weight - drag) / mass;
            y(1) = displacement;
            y(2) = velocity;

        case EXIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);

        otherwise
            error('Invalid mode');
    end
end