%% Generated by RAG ModelSpec pipeline
% task_goal: 
% model_id: transfer_function_step
% generator_strategy: template
function [y, f] = transfer_function_step(mode, time, Ts, x, u)
    INIT = 10102;  % 初始化模式
    CONT = 10103;  % 连续计算模式
    OUT  = 10111;  % 输出模式
    EXIT = 10106;  % 退出模式

    num = [1];
    den = [1 3 2];
    [A, B, C, D] = tf2ss(num, den);

    state_dim = max(0, size(A, 1));
    output_dim = max(0, size(C, 1));
    input_dim = max(0, 1);

    if nargin < 4 || isempty(x)
        x = zeros(state_dim, 1);
    else
        x = x(:);
    end
    if state_dim == 0
        x = zeros(0, 1);
    elseif numel(x) < state_dim
        x = [x; zeros(state_dim - numel(x), 1)];
    elseif numel(x) > state_dim
        x = x(1:state_dim);
    end

    if nargin < 5 || isempty(u)
        u = 1;
    else
        u = u(:);
    end
    if input_dim == 0
        u = zeros(0, 1);
    elseif numel(u) < input_dim
        u = [u; zeros(input_dim - numel(u), 1)];
    elseif numel(u) > input_dim
        u = u(1:input_dim);
    end

    switch mode
        case INIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            step_val = u(1);
            if time < 0
                step_val = 0;
            end
            response = C * x + D * step_val;
            response = response(:);
            y = response;
            f = A * x + B * step_val;

        case CONT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            step_val = u(1);
            if time < 0
                step_val = 0;
            end
            response = C * x + D * step_val;
            response = response(:);
            y = response;
            f = A * x + B * step_val;

        case OUT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            step_val = u(1);
            if time < 0
                step_val = 0;
            end
            response = C * x + D * step_val;
            response = response(:);
            y = response;

        case EXIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);

        otherwise
            error('Invalid mode');
    end
end