"""
Knowledge entries for MATLAB/Simulink model generation.
"""

from __future__ import annotations

from typing import Dict, List


MATLAB_MODEL_KNOWLEDGE: List[Dict] = [
    {
        "model_id": "transfer_function_step",
        "name": "Transfer Function Step Response",
        "category": "control",
        "keywords": ["transfer function", "tf", "step", "传递函数", "阶跃响应", "控制系统"],
        "description": "Create a transfer function model and run step response.",
        "default_params": {
            "numerator": "[1]",
            "denominator": "[1 3 2]",
            "stop_time": 10,
        },
        "examples": [
            "构建一个二阶传递函数并画阶跃响应",
            "build tf step response with denominator [1 3 2]",
        ],
    },
    {
        "model_id": "state_space_response",
        "name": "State Space Simulation",
        "category": "control",
        "keywords": ["state space", "ss", "状态空间", "lsim", "状态变量"],
        "description": "Build a state-space model and simulate output with lsim.",
        "default_params": {
            "A": "[0 1; -2 -3]",
            "B": "[0; 1]",
            "C": "[1 0]",
            "D": "0",
            "stop_time": 10,
        },
        "examples": [
            "生成状态空间模型仿真代码",
            "simulate state space system with lsim",
        ],
    },
    {
        "model_id": "pid_simulink_loop",
        "name": "PID Closed Loop in Simulink",
        "category": "simulink_control",
        "keywords": ["pid", "simulink", "闭环", "控制器", "调参", "直流电机"],
        "description": "Create a Simulink closed-loop model with PID and transfer function plant.",
        "default_params": {
            "kp": 1.2,
            "ki": 0.8,
            "kd": 0.02,
            "numerator": "[1]",
            "denominator": "[0.5 1]",
            "stop_time": 20,
        },
        "examples": [
            "构建PID闭环控制的Simulink模型",
            "build a simulink pid loop for dc motor",
        ],
    },
    {
        "model_id": "mass_spring_damper_ode",
        "name": "Mass-Spring-Damper ODE Model",
        "category": "physical_modeling",
        "keywords": ["mass spring damper", "ode45", "质量弹簧阻尼", "机械系统", "二阶系统"],
        "description": "Build and simulate a mass-spring-damper model using ode45.",
        "default_params": {
            "m": 1.0,
            "c": 0.5,
            "k": 20.0,
            "x0": "[0; 0]",
            "stop_time": 15,
        },
        "examples": [
            "生成质量弹簧阻尼系统仿真代码",
            "simulate mass spring damper with ode45",
        ],
    },
    {
        "model_id": "kalman_tracking",
        "name": "Kalman Filter Tracking",
        "category": "estimation",
        "keywords": ["kalman", "滤波", "状态估计", "跟踪", "观测噪声"],
        "description": "Create a 1D constant velocity tracking example with Kalman filter.",
        "default_params": {
            "dt": 0.1,
            "steps": 200,
            "process_noise": 0.01,
            "measurement_noise": 0.1,
        },
        "examples": [
            "构建卡尔曼滤波跟踪模型",
            "build kalman filter tracking script",
        ],
    },
    {
        "model_id": "arx_identification",
        "name": "ARX System Identification",
        "category": "identification",
        "keywords": ["arx", "system identification", "辨识", "输入输出建模", "iddata"],
        "description": "Generate ARX identification pipeline from synthetic data.",
        "default_params": {
            "na": 2,
            "nb": 2,
            "nk": 1,
            "samples": 500,
        },
        "examples": [
            "生成ARX系统辨识模型",
            "identify system with arx model",
        ],
    },
    {
        "model_id": "mpc_control",
        "name": "Model Predictive Control Demo",
        "category": "advanced_control",
        "keywords": ["mpc", "predictive control", "模型预测控制", "约束控制"],
        "description": "Create an MPC controller for a simple plant with constraints.",
        "default_params": {
            "ts": 0.1,
            "prediction_horizon": 20,
            "control_horizon": 5,
            "stop_time": 30,
        },
        "examples": [
            "构建MPC控制模型",
            "build model predictive control demo in matlab",
        ],
    },
    {
        "model_id": "fft_lowpass_filter",
        "name": "FFT-based Signal Filter",
        "category": "signal_processing",
        "keywords": ["fft", "signal", "滤波", "低通", "频域"],
        "description": "Generate noisy signal and apply FFT low-pass filtering.",
        "default_params": {
            "fs": 1000,
            "duration": 2.0,
            "cutoff_hz": 40,
        },
        "examples": [
            "生成FFT低通滤波模型",
            "build frequency domain low-pass filtering script",
        ],
    },
    {
        "model_id": "battery_rc_model",
        "name": "Battery 1-RC Equivalent Model",
        "category": "energy",
        "keywords": ["battery", "rc model", "电池", "等效电路", "soc"],
        "description": "Build a simple battery equivalent circuit simulation (1-RC model).",
        "default_params": {
            "capacity_ah": 2.3,
            "r0": 0.03,
            "r1": 0.015,
            "c1": 2400,
            "stop_time": 2000,
        },
        "examples": [
            "构建电池一阶RC等效模型",
            "simulate battery rc equivalent circuit in matlab",
        ],
    },
    {
        "model_id": "pv_iv_curve",
        "name": "PV I-V Curve Model",
        "category": "energy",
        "keywords": ["pv", "solar", "光伏", "i-v", "组件模型"],
        "description": "Build a photovoltaic module I-V and P-V curve script.",
        "default_params": {
            "isc": 8.2,
            "voc": 37.5,
            "n_cells": 60,
            "temperature": 25,
        },
        "examples": [
            "生成光伏组件IV曲线模型",
            "build solar pv iv curve matlab model",
        ],
    },
    {
        "model_id": "robot_2dof_kinematics",
        "name": "2-DOF Robot Kinematics",
        "category": "robotics",
        "keywords": ["robot", "2dof", "kinematics", "机器人", "逆解", "机械臂"],
        "description": "Build forward/inverse kinematics demo for 2-link planar robot.",
        "default_params": {
            "l1": 0.6,
            "l2": 0.4,
            "x_target": 0.7,
            "y_target": 0.2,
        },
        "examples": [
            "构建二自由度机械臂运动学模型",
            "build 2dof robot kinematics matlab script",
        ],
    },
    {
        "model_id": "rocket_launch_1d",
        "name": "1D Rocket Launch Dynamics",
        "category": "aerospace",
        "template_family": "launch_dynamics",
        "domain_tags": ["aerospace", "launch_dynamics", "military_equipment", "propulsion"],
        "equation_fragments": ["constant_thrust", "mass_depletion", "quadratic_drag_air", "gravity_scalar"],
        "keywords": [
            'rocket',
            'launch',
            'vertical launch',
            'rocket launch',
            'launch dynamics',
            'propulsion',
            'fuel mass',
            'burn rate',
            'mass depletion',
            'thrust-to-weight ratio',
            'air drag',
            '1d launch',
            'vertical ascent',
            'single-axis ascent',
            'atmospheric ascent',
            '火箭',
            '火箭发射',
            '垂直发射',
            '升空',
            '运载火箭',
            '发射动力学',
            '一维发射',
            '一维垂直发射',
            '垂直升空',
            '发射段动力学',
            '推进剂',
            '燃料质量',
            '燃烧速率',
            '质量递减',
            '推重比',
            '空气阻力',
            '航天',

        ],
        "description": "Simulate 1D vertical rocket launch with thrust, drag, gravity and fuel consumption.",
        "default_params": {
            "mass0": 500.0,
            "fuel_mass": 180.0,
            "burn_rate": 2.5,
            "thrust": 16000.0,
            "drag_coeff": 0.55,
            "area": 0.8,
            "air_density": 1.225,
            "g": 9.81,
            "dt": 0.05,
            "stop_time": 120.0,
        },
        "examples": [
            '生成一个一维火箭垂直发射模型，考虑推力、重力、空气阻力和燃料消耗',
            '构建运载火箭起飞阶段的 MATLAB 模型，给定起飞质量、推进剂质量和燃烧速率',
            '建立航空航天发射模型，考虑推重比、燃料质量、燃烧速率和空气阻力',
            'simulate 1d vertical rocket launch with thrust drag gravity and fuel burn',
            'build rocket launch dynamics model in matlab with mass depletion and air drag',
            '做一个火箭一维垂直发射动力学模型，关注推重比、燃料消耗和空气阻力',
            '构建大气层内单轴升空仿真，不是二维弹道轨迹，也不是卫星入轨后的轨道传播',
            'simulate vertical rocket ascent in atmosphere with thrust-to-weight and fuel burn, not planar trajectory or orbital propagation',

        ],
    },
    {
        "model_id": "missile_flight_2d",
        "name": "2D Missile Flight Dynamics",
        "category": "aerospace_defense",
        "template_family": "trajectory_ode",
        "domain_tags": ["aerospace", "military_equipment", "missile", "flight_dynamics"],
        "equation_fragments": ["constant_thrust_vector", "quadratic_drag_planar", "gravity_planar"],
        "keywords": [
            'missile',
            'interceptor',
            'trajectory',
            'flight dynamics',
            'planar trajectory',
            'ballistic trajectory',
            'launch angle',
            'boost phase',
            'intercept trajectory',
            'air drag',
            '2d trajectory',
            'planar flight',
            'range-altitude',
            '导弹',
            '拦截弹',
            '导弹轨迹',
            '飞行轨迹',
            '二维弹道',
            '二维轨迹',
            '平面弹道',
            '弹道飞行',
            '射程高度轨迹',
            '拦截轨迹',
            '发射角',
            '仰角',
            '推进段',
            '末制导',
            '空气阻力',
            '军工',

        ],
        "description": "Simulate 2D missile flight with thrust, drag, gravity and launch angle.",
        "default_params": {
            "mass0": 120.0,
            "thrust": 6000.0,
            "drag_coeff": 0.32,
            "area": 0.08,
            "air_density": 1.225,
            "g": 9.81,
            "launch_angle_deg": 45.0,
            "init_speed": 30.0,
            "burn_time": 8.0,
            "dt": 0.02,
            "stop_time": 60.0,
        },
        "examples": [
            '构建二维导弹飞行轨迹模型，考虑发射角、初速度、推力和空气阻力',
            '生成拦截弹二维飞行弹道 MATLAB 脚本，考虑推进段时间和气动阻力',
            '做一个导弹平面轨迹仿真，给定初始质量、发射仰角和发动机推力',
            'simulate 2d missile flight with launch angle initial speed thrust and drag',
            'build planar interceptor trajectory model in matlab with boost phase and gravity',
            '做一个二维导弹弹道轨迹模型，给定发射角、初速度和推力，不是垂直发射',
            '构建平面 x-y 弹道轨迹仿真，输出射程和高度，不是只看一维垂直升空',
            'build 2d planar missile trajectory with launch angle and initial speed, not 1d vertical launch',

        ],
    },
    {
        "model_id": "satellite_orbit_2body",
        "name": "2-Body Satellite Orbit",
        "category": "aerospace_orbit",
        "template_family": "orbital_dynamics",
        "domain_tags": ["aerospace", "spacecraft", "orbit", "space"],
        "equation_fragments": ["two_body_gravity_planar"],
        "keywords": [
            'satellite',
            'orbit',
            'orbital',
            'spacecraft',
            'two-body',
            'orbital dynamics',
            'low earth orbit',
            'gravitational parameter',
            'orbital speed',
            'orbital period',
            'orbit propagation',
            'kepler orbit',
            'on-orbit motion',
            '卫星',
            '轨道',
            '轨道传播',
            '二体问题',
            '二体轨道',
            '航天器',
            '近地轨道',
            '引力参数',
            '轨道高度',
            '轨道速度',
            '轨道周期',
            '空间轨道',
            '入轨后轨道',
            '在轨运行',
            '开普勒轨道',

        ],
        "description": "Simulate a planar two-body satellite orbit around Earth.",
        "default_params": {
            "mu": 3.986e14,
            "earth_radius": 6.371e6,
            "altitude0": 4.0e5,
            "v0": 7670.0,
            "dt": 5.0,
            "stop_time": 5400.0,
        },
        "examples": [
            '构建卫星二体轨道传播模型，给定轨道高度和初始轨道速度',
            '生成近地轨道航天器二维轨道 MATLAB 脚本，考虑地球引力参数',
            '做一个卫星轨道动力学模型，输入初始高度、轨道速度和仿真时长',
            'simulate 2-body satellite orbit in matlab with altitude and orbital speed',
            'build spacecraft orbital dynamics model with gravitational parameter and time step',
            '做一个卫星入轨后的二体轨道传播，不是火箭发射段',
            '构建地心二体轨道模型，关注轨道周期和轨迹闭合，不考虑推力和空气阻力',
            'simulate on-orbit two-body propagation, not launch ascent with thrust or atmospheric drag',

        ],
    },
    {
        "model_id": "torpedo_underwater_launch_1d",
        "name": "1D Torpedo Underwater Launch",
        "category": "naval_weapon",
        "template_family": "underwater_launch",
        "domain_tags": ["military_equipment", "naval_weapon", "underwater", "launch_dynamics"],
        "equation_fragments": ["constant_thrust", "quadratic_drag_water", "gravity_scalar", "buoyancy_scalar"],
        "keywords": [
            'torpedo',
            'submarine',
            'underwater',
            'underwater launch',
            'tube launch',
            'buoyancy',
            'water drag',
            'displaced volume',
            'naval weapon',
            'hydrodynamic',
            'tube ejection',
            'submerged launch',
            '鱼雷',
            '潜艇',
            '水下',
            '水下发射',
            '出管',
            '水下出管',
            '浮力',
            '水阻',
            '水中阻力',
            '排水体积',
            '排开体积',
            '潜射出筒',
            '水下弹射',
            '管内发射',
            '水下推进',
            '军工装备',

        ],
        "description": "Simulate 1D torpedo underwater launch with thrust, drag, buoyancy and gravity.",
        "default_params": {
            "mass": 180.0,
            "thrust": 3200.0,
            "drag_coeff": 0.35,
            "area": 0.045,
            "water_density": 1000.0,
            "displaced_volume": 0.16,
            "g": 9.81,
            "dt": 0.02,
            "stop_time": 25.0,
        },
        "examples": [
            '构建一个潜艇水下发射鱼雷模型，考虑水下阻力、浮力和推力',
            '生成鱼雷出管阶段的一维动力学仿真，给定鱼雷质量、推力和排水体积',
            '做一个水下武器发射模型，考虑海水密度、水阻系数和浮力',
            'simulate torpedo underwater launch with drag buoyancy and thrust',
            'build 1d underwater launch model for torpedo with displaced volume and water density',
            '做一个鱼雷水下出管发射模型，考虑浮力和水阻，不是火箭升空',
            '构建潜艇武器出管一维动力学，关注排水体积、海水密度和浮力',
            'build submerged tube-ejection dynamics with buoyancy and water drag, not atmospheric rocket launch',

        ],
    },
    {
        "model_id": "radar_target_tracking_2d",
        "name": "2D Radar Target Tracking",
        "category": "military_sensing",
        "template_family": "tracking_estimation",
        "domain_tags": ["military_equipment", "battlefield_situation", "radar", "tracking"],
        "equation_fragments": ["cv_state_transition", "noisy_measurement", "kalman_filter_update"],
        "keywords": [
            'radar',
            'tracking',
            'target tracking',
            'kalman',
            'surveillance',
            'measurement noise',
            'process noise',
            'track estimation',
            'target trajectory',
            'single-target tracking',
            'single-sensor tracking',
            'state estimation',
            '雷达',
            '雷达目标',
            '目标跟踪',
            '单目标跟踪',
            '航迹',
            '航迹跟踪',
            '卡尔曼滤波',
            '观测噪声',
            '过程噪声',
            '跟踪估计',
            '状态估计',
            '预警',
            '探测',
            '态势感知',

        ],
        "description": "Generate 2D constant-velocity radar tracking with noisy observations and Kalman filtering.",
        "default_params": {
            "dt": 1.0,
            "steps": 120,
            "process_noise": 0.05,
            "measurement_noise": 20.0,
            "x0": 0.0,
            "y0": 0.0,
            "target_speed_x": 220.0,
            "target_speed_y": 40.0,
            "stop_time": 120.0,
        },
        "examples": [
            '构建雷达二维目标跟踪模型，考虑观测噪声、过程噪声和目标速度',
            '生成战场预警场景下的目标航迹跟踪 MATLAB 脚本，使用卡尔曼滤波',
            '做一个雷达目标跟踪估计模型，给定横向速度、纵向速度和测量噪声',
            'build 2d radar target tracking with kalman filter and noisy measurements',
            'simulate radar track estimation with process noise measurement noise and target velocity',
            '做一个单雷达目标跟踪与卡尔曼滤波，不是战场态势感知',
            '构建二维航迹估计模型，输出真值、量测和滤波估计，不是覆盖融合态势评估',
            'build single-sensor radar target tracking with kalman filter, not battlefield awareness coverage fusion',

        ],
    },
    {
        "model_id": "lanchester_battle_attrition",
        "name": "Lanchester Battle Attrition",
        "category": "battlefield_situation",
        "template_family": "combat_attrition",
        "domain_tags": ["battlefield_situation", "combat", "force_comparison", "military_analysis"],
        "equation_fragments": ["lanchester_square_law"],
        "keywords": [
            'battlefield',
            'lanchester',
            'attrition',
            'red blue',
            'combat',
            'force comparison',
            'battle damage',
            'combat effectiveness',
            'situation awareness',
            'force attrition',
            'kill coefficient',
            'force depletion',
            '战场',
            '战场态势',
            '红蓝对抗',
            '红蓝兵力',
            '兵力消耗',
            '兵力对抗',
            '战损',
            '兰彻斯特',
            '杀伤系数',
            '力量对比',
            '作战效能',
            '兵力衰减',
            '敌我态势',
            '态势评估',

        ],
        "description": "Simulate red-blue force attrition using Lanchester combat equations.",
        "default_params": {
            "red0": 120.0,
            "blue0": 100.0,
            "alpha": 0.035,
            "beta": 0.04,
            "dt": 0.1,
            "stop_time": 40.0,
        },
        "examples": [
            '构建红蓝双方兵力消耗模型，分析战损与作战效能变化',
            '生成基于兰彻斯特定律的战场对抗 MATLAB 脚本，给定双方初始兵力和杀伤系数',
            '做一个战场态势层的兵力演化模型，分析红蓝力量对比',
            'simulate battlefield attrition with lanchester equations and red blue forces',
            'build combat attrition model with initial forces and kill coefficients in matlab',
            '做一个红蓝兵力消耗兰彻斯特模型，不是态势感知覆盖融合',
            '构建双方兵力随时间衰减的对抗模型，关注红蓝战损和杀伤系数',
            'simulate red-blue force attrition with Lanchester equations, not battlefield awareness coverage fusion',

        ],
    },
]


def get_model_catalog() -> List[Dict]:
    return MATLAB_MODEL_KNOWLEDGE
