%% Generated by RAG ModelSpec pipeline
% task_goal: 构建一个红蓝双方兵力消耗模型，用于战场态势分析
% model_id: lanchester_battle_attrition
% assumptions:
%   - 红蓝双方兵力连续变化
%   - 杀伤率在仿真窗口内视为常数
% evidence:
%   - model=lanchester_battle_attrition, score=11.4217, id=160
%   - model=lanchester_battle_attrition, score=9.7, id=161
%   - model=torpedo_underwater_launch_1d, score=9.5313, id=141
%   - model=lanchester_battle_attrition, score=6.9628, id=162
%   - model=lanchester_battle_attrition, score=6.8336, id=163
%% Auto-generated MATLAB model: Lanchester Battle Attrition
clear; clc; close all;

red0 = 120.0;
blue0 = 100.0;
alpha = 0.035;
beta = 0.04;
dt = 0.1;
T = 40.0;

t = 0:dt:T;
N = numel(t);
red = zeros(N,1);
blue = zeros(N,1);
red(1) = red0;
blue(1) = blue0;

for k = 2:N
    d_red = -alpha * blue(k-1);
    d_blue = -beta * red(k-1);
    red(k) = max(0, red(k-1) + d_red * dt);
    blue(k) = max(0, blue(k-1) + d_blue * dt);
    if red(k) <= 0 || blue(k) <= 0
        red(k+1:end) = red(k);
        blue(k+1:end) = blue(k);
        break;
    end
end

fprintf('Final red force: %.2f
', red(end));
fprintf('Final blue force: %.2f
', blue(end));
fprintf('Combat outcome index (red-blue): %.2f
', red(end) - blue(end));

figure('Name', 'Lanchester Battle Attrition');
subplot(1,2,1);
plot(t, red, 'r', 'LineWidth', 1.8); hold on;
plot(t, blue, 'b', 'LineWidth', 1.8);
grid on; xlabel('Time'); ylabel('Force Level'); title('Force Attrition'); legend('Red', 'Blue');
subplot(1,2,2);
plot(red, blue, 'k', 'LineWidth', 1.8);
grid on; xlabel('Red Force'); ylabel('Blue Force'); title('Phase Portrait');
