%% Generated by RAG ModelSpec pipeline
% task_goal: 构建一个无人机飞行模型 继续构建 template_family=trajectory_ode
% model_id: missile_flight_2d
% generator_strategy: ir_composable_renderer
% template_family: trajectory_ode
% governing_form: ode
% solver: discrete_euler
% codegen_strategy: legacy_spec_adapter
% equation_fragments: constant_thrust_vector, quadratic_drag_planar, gravity_planar
% render_blocks: meta:comments, workspace:clear, setup:trajectory_ode:fragment_flags, declare:trajectory_ode:parameters, setup:trajectory_ode:time_grid, setup:trajectory_ode:state_arrays, setup:trajectory_ode:initial_conditions, solver:trajectory_ode:loop_begin, fragment:trajectory_ode:constant_thrust_vector, fragment:trajectory_ode:quadratic_drag_planar, fragment:trajectory_ode:gravity_planar, update:trajectory_ode:state, solver:trajectory_ode:loop_end, output:trajectory_ode:plots
% assumptions:
%   - 平面二维运动
%   - 忽略姿态高阶耦合
% evidence:
%   - model=missile_flight_2d, score=12.2064, id=128
%   - model=missile_flight_2d, score=11.1369, id=124
%   - model=missile_flight_2d, score=10.5828, id=127
%   - model=missile_flight_2d, score=9.7054, id=123
%   - model=missile_flight_2d, score=9.6191, id=126
%% IR-block-composed MATLAB model: 2D Missile Flight Dynamics
% family: trajectory_ode
% governing_form: ode
% solver: discrete_euler
% codegen_strategy: legacy_spec_adapter
% render_block: meta:comments
% render_block: workspace:clear
% render_block: setup:trajectory_ode:fragment_flags
% render_block: declare:trajectory_ode:parameters
% render_block: setup:trajectory_ode:time_grid
% render_block: setup:trajectory_ode:state_arrays
% render_block: setup:trajectory_ode:initial_conditions
% render_block: solver:trajectory_ode:loop_begin
% render_block: fragment:trajectory_ode:constant_thrust_vector
% render_block: fragment:trajectory_ode:quadratic_drag_planar
% render_block: fragment:trajectory_ode:gravity_planar
% render_block: update:trajectory_ode:state
% render_block: solver:trajectory_ode:loop_end
% render_block: output:trajectory_ode:plots
% fragment: constant_thrust_vector | library/native | equation_fragments | constant thrust projected to body axis | F_thrust = T * [cos(theta), sin(theta)]
% fragment: quadratic_drag_planar | library/native | equation_fragments | planar quadratic drag | F_drag = 0.5 * rho * Cd * A * ||v||^2 * v/||v||
% fragment: gravity_planar | library/native | equation_fragments | planar gravity | a_g = [0, -g]
% equation: dx/dt = vx
% equation: dy/dt = vy
% equation: m dv/dt = thrust_vector - drag_vector - gravity_vector

clear; clc; close all;

use_thrust = true;
use_drag = true;
use_gravity = true;

mass0 = 500.0;
thrust = 100000.0;
Cd = 0.32;
A = 0.08;
rho = 1.225;
g = 9.81;
launch_angle_deg = 85.0;
init_speed = 100.0;
burn_time = 8.0;
dt = 0.02;
T = 60.0;

t = 0:dt:T;
N = numel(t);

x = zeros(N,1);
y = zeros(N,1);
vx = zeros(N,1);
vy = zeros(N,1);
ax = zeros(N,1);
ay = zeros(N,1);

theta = deg2rad(launch_angle_deg);
vx(1) = init_speed * cos(theta);
vy(1) = init_speed * sin(theta);

for k = 2:N
    speed = hypot(vx(k-1), vy(k-1));

    if use_thrust
        current_thrust = thrust * (t(k-1) <= burn_time);
        thrust_x = current_thrust * cos(theta);
        thrust_y = current_thrust * sin(theta);
    else
        thrust_x = 0;
        thrust_y = 0;
    end

    if use_drag && speed > 1e-8
        drag = 0.5 * rho * Cd * A * speed^2;
        drag_x = drag * vx(k-1) / speed;
        drag_y = drag * vy(k-1) / speed;
    else
        drag_x = 0;
        drag_y = 0;
    end

    gravity_y = g * use_gravity;

    ax(k) = (thrust_x - drag_x) / max(mass0, 1e-9);
    ay(k) = (thrust_y - drag_y) / max(mass0, 1e-9) - gravity_y;
    vx(k) = vx(k-1) + ax(k) * dt;
    vy(k) = vy(k-1) + ay(k) * dt;
    x(k) = x(k-1) + vx(k) * dt;
    y(k) = max(0, y(k-1) + vy(k) * dt);
    if k > 5 && y(k) <= 0 && vy(k) < 0
        x(k+1:end) = x(k);
        y(k+1:end) = 0;
        vx(k+1:end) = vx(k);
        vy(k+1:end) = 0;
        break;
    end

end

figure('Name', 'Trajectory Dynamics 2D');
subplot(2,2,1); plot(x, y, 'LineWidth', 1.8); grid on; xlabel('X (m)'); ylabel('Y (m)'); title('IR-Block Trajectory');
subplot(2,2,2); plot(t, vx, 'LineWidth', 1.5); hold on; plot(t, vy, 'LineWidth', 1.5); grid on; legend('v_x', 'v_y'); xlabel('Time (s)'); ylabel('Velocity (m/s)');
subplot(2,2,3); plot(t, hypot(vx, vy), 'LineWidth', 1.5); grid on; xlabel('Time (s)'); ylabel('Speed (m/s)');
subplot(2,2,4); plot(t, ax, 'LineWidth', 1.5); hold on; plot(t, ay, 'LineWidth', 1.5); grid on; legend('a_x', 'a_y'); xlabel('Time (s)'); ylabel('Acceleration (m/s^2)');