%% Generated by RAG ModelSpec pipeline
% task_goal: 生成PID闭环Simulink模型，kp=1.2,ki=0.6,kd=0.01，仿真20秒
% model_id: pid_simulink_loop
% assumptions:
%   - kp=1.2, ki=0.6, kd=0.01
% evidence:
%   - model=pid_simulink_loop, score=15.0, id=20
%   - model=pid_simulink_loop, score=5.0, id=21
%   - model=arx_identification, score=2.8, id=51
%   - model=fft_lowpass_filter, score=2.8, id=71
%   - model=state_space_response, score=2.4, id=11
%% Auto-generated MATLAB model: PID closed-loop Simulink
clear; clc; close all;

modelName = 'auto_pid_loop_model';
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
new_system(modelName);
open_system(modelName);

add_block('simulink/Sources/Step', [modelName '/Step'], ...
    'Position', [30 80 60 110]);
add_block('simulink/Math Operations/Sum', [modelName '/Sum'], ...
    'Inputs', '+-', 'Position', [100 78 120 112]);
add_block('simulink/Continuous/PID Controller', [modelName '/PID'], ...
    'P', '1.2', 'I', '0.6', 'D', '0.01', ...
    'Position', [170 70 250 120]);
add_block('simulink/Continuous/Transfer Fcn', [modelName '/Plant'], ...
    'Numerator', '[1]', 'Denominator', '[0.5 1]', ...
    'Position', [300 75 380 115]);
add_block('simulink/Sinks/Scope', [modelName '/Scope'], ...
    'Position', [450 80 480 110]);

add_line(modelName, 'Step/1', 'Sum/1');
add_line(modelName, 'Sum/1', 'PID/1');
add_line(modelName, 'PID/1', 'Plant/1');
add_line(modelName, 'Plant/1', 'Scope/1');
add_line(modelName, 'Plant/1', 'Sum/2');

set_param(modelName, 'StopTime', '20.0');
sim(modelName);
save_system(modelName, [modelName '.slx']);
