%% Generated by RAG ModelSpec pipeline
% task_goal: 生成一个火箭发射模型
% model_id: rocket_launch_1d
% generator_strategy: ir_composable_renderer
% template_family: launch_dynamics
% governing_form: ode
% solver: discrete_euler
% codegen_strategy: ir_composable_renderer
% equation_fragments: constant_thrust, mass_depletion, quadratic_drag_air, gravity_scalar
% render_blocks: meta:comments, workspace:clear, setup:launch_dynamics:fragment_flags, declare:launch_dynamics:parameters, setup:launch_dynamics:time_grid, setup:launch_dynamics:state_arrays, solver:launch_dynamics:loop_begin, fragment:launch_dynamics:mass_depletion, fragment:launch_dynamics:constant_thrust, fragment:launch_dynamics:quadratic_drag_air, fragment:launch_dynamics:gravity_scalar, update:launch_dynamics:state, solver:launch_dynamics:loop_end, postprocess:launch_dynamics:metrics, output:launch_dynamics:plots
% assumptions:
%   - 一维竖直方向运动
%   - 考虑推力、阻力和重力
%   - 未明确参数使用默认环境值
% evidence:
%   - model=rocket_launch_1d, score=17.2376, id=111
%   - model=rocket_launch_1d, score=9.7, id=112
%   - model=rocket_launch_1d, score=8.7941, id=110
%   - model=rocket_launch_1d, score=8.0018, id=113
%   - model=torpedo_underwater_launch_1d, score=6.8474, id=141
%% IR-block-composed MATLAB model: 1D Rocket Launch Dynamics\n% family: launch_dynamics
% governing_form: ode
% solver: discrete_euler
% codegen_strategy: ir_composable_renderer
% render_block: meta:comments
% render_block: workspace:clear
% render_block: setup:launch_dynamics:fragment_flags
% render_block: declare:launch_dynamics:parameters
% render_block: setup:launch_dynamics:time_grid
% render_block: setup:launch_dynamics:state_arrays
% render_block: solver:launch_dynamics:loop_begin
% render_block: fragment:launch_dynamics:mass_depletion
% render_block: fragment:launch_dynamics:constant_thrust
% render_block: fragment:launch_dynamics:quadratic_drag_air
% render_block: fragment:launch_dynamics:gravity_scalar
% render_block: update:launch_dynamics:state
% render_block: solver:launch_dynamics:loop_end
% render_block: postprocess:launch_dynamics:metrics
% render_block: output:launch_dynamics:plots
% fragment: constant_thrust | constant thrust term | F_thrust = T
% fragment: mass_depletion | linear mass depletion during burn | m(t) = m0 - burn_rate * t
% fragment: quadratic_drag_air | quadratic aerodynamic drag | F_drag = 0.5 * rho_air * Cd * A * v * abs(v)
% fragment: gravity_scalar | scalar gravity term | F_gravity = m * g
% equation: dh/dt = v
% equation: m dv/dt = thrust - drag - m g
% equation: m(t) = m0 - burn_rate * t during burn

clear; clc; close all;

use_thrust = true;\nuse_mass_depletion = true;\nuse_drag = true;\nuse_gravity = true;

mass0 = 500.0;\nfuel_mass = 180.0;\nburn_rate = 2.5;\nthrust = 16000.0;\nCd = 0.55;\nA = 0.8;\nrho = 1.225;\ng = 9.81;\ndt = 0.05;\nT = 120.0;

t = 0:dt:T;\nN = numel(t);

h = zeros(N,1);\nv = zeros(N,1);\na = zeros(N,1);\nm = zeros(N,1);

for k = 1:N\n    tk = t(k);

    if use_mass_depletion\n        burned = min(fuel_mass, burn_rate * tk);\n        m(k) = max(mass0 - burned, mass0 - fuel_mass);\n    else\n        burned = 0;\n        m(k) = mass0;\n    end

    if use_thrust\n        if use_mass_depletion\n            current_thrust = thrust * (burned < fuel_mass);\n        else\n            current_thrust = thrust;\n        end\n    else\n        current_thrust = 0;\n    end

    if use_drag\n        drag = 0.5 * rho * Cd * A * v(max(k-1,1)) * abs(v(max(k-1,1)));\n    else\n        drag = 0;\n    end

    if use_gravity\n        weight = m(k) * g;\n    else\n        weight = 0;\n    end

    a(k) = (current_thrust - drag - weight) / max(m(k), 1e-9);\n    if k > 1\n        v(k) = v(k-1) + a(k) * dt;\n        h(k) = max(0, h(k-1) + v(k) * dt);\n    end

end

[max_h, idx] = max(h);\nfprintf('Max altitude: %.2f m at t = %.2f s\n', max_h, t(idx));\nfprintf('Final velocity: %.2f m/s\n', v(end));

figure('Name', 'Launch Dynamics 1D');\nsubplot(3,1,1); plot(t, h, 'LineWidth', 1.6); grid on; ylabel('Altitude (m)'); title('IR-Block Launch Dynamics');\nsubplot(3,1,2); plot(t, v, 'LineWidth', 1.6); grid on; ylabel('Velocity (m/s)');\nsubplot(3,1,3); plot(t, a, 'LineWidth', 1.6); grid on; ylabel('Acceleration (m/s^2)'); xlabel('Time (s)');