%% Generated by RAG ModelSpec pipeline
% task_goal: 生成一个火箭发射模型
% model_id: rocket_launch_1d
% assumptions:
%   - 使用默认参数补全未明确指定项
% evidence:
%   - model=rocket_launch_1d, score=8.0, id=110
%   - model=rocket_launch_1d, score=4.2, id=111
%   - model=pid_simulink_loop, score=1.4, id=21
%   - model=arx_identification, score=1.4, id=51
%   - model=fft_lowpass_filter, score=1.4, id=71
%% Auto-generated MATLAB model: 1D Rocket Launch Dynamics
clear; clc; close all;

mass0 = 500.0;             % initial total mass (kg)
fuel_mass = 180.0;     % fuel mass (kg)
burn_rate = 2.5;     % fuel burn rate (kg/s)
thrust = 16000.0;           % engine thrust (N)
Cd = 0.55;           % drag coefficient
A = 0.8;                  % frontal area (m^2)
rho = 1.225;         % air density (kg/m^3)
g = 9.81;                     % gravity (m/s^2)
dt = 0.05;                   % simulation step (s)
T = 120.0;             % total simulation time (s)

t = 0:dt:T;
N = numel(t);
h = zeros(N,1);   % altitude
v = zeros(N,1);   % velocity
a = zeros(N,1);   % acceleration
m = zeros(N,1);   % mass

for k = 1:N
    tk = t(k);
    burned = min(fuel_mass, burn_rate * tk);
    m(k) = mass0 - burned;

    if burned < fuel_mass
        current_thrust = thrust;
    else
        current_thrust = 0;
    end

    drag = 0.5 * rho * Cd * A * v(max(k-1,1)) * abs(v(max(k-1,1)));
    weight = m(k) * g;
    a(k) = (current_thrust - drag - weight) / m(k);

    if k > 1
        v(k) = v(k-1) + a(k) * dt;
        h(k) = max(0, h(k-1) + v(k) * dt);
    end
end

[max_h, idx] = max(h);
fprintf('Max altitude: %.2f m at t = %.2f s\n', max_h, t(idx));
fprintf('Final velocity: %.2f m/s\n', v(end));

figure('Name', 'Rocket Launch 1D');
subplot(3,1,1); plot(t, h, 'LineWidth', 1.6); grid on; ylabel('Altitude (m)');
title('1D Rocket Launch Dynamics');
subplot(3,1,2); plot(t, v, 'LineWidth', 1.6); grid on; ylabel('Velocity (m/s)');
subplot(3,1,3); plot(t, a, 'LineWidth', 1.6); grid on; ylabel('Acceleration (m/s^2)'); xlabel('Time (s)');
