%% Generated by RAG ModelSpec pipeline
% task_goal: 生成一维火箭发射模型
% model_id: rocket_launch_1d
% generator_strategy: ir_composable_renderer
% template_family: launch_dynamics
% governing_form: ode
% solver: discrete_euler
% codegen_strategy: ir_composable_renderer
% equation_fragments: constant_thrust, mass_depletion, quadratic_drag_air, gravity_scalar
% render_blocks: meta:comments, workspace:clear, setup:launch_dynamics:fragment_flags, declare:launch_dynamics:parameters, setup:launch_dynamics:time_grid, setup:launch_dynamics:state_arrays, solver:launch_dynamics:loop_begin, fragment:launch_dynamics:mass_depletion, fragment:launch_dynamics:constant_thrust, fragment:launch_dynamics:quadratic_drag_air, fragment:launch_dynamics:gravity_scalar, update:launch_dynamics:state, solver:launch_dynamics:loop_end, postprocess:launch_dynamics:metrics, output:launch_dynamics:plots
% assumptions:
%   - vertical launch
%% IR-block-composed MATLAB model: Open IR Rocket Demo
% family: launch_dynamics
% governing_form: ode
% solver: discrete_euler
% codegen_strategy: ir_composable_renderer
% render_block: meta:comments
% render_block: workspace:clear
% render_block: setup:launch_dynamics:fragment_flags
% render_block: declare:launch_dynamics:parameters
% render_block: setup:launch_dynamics:time_grid
% render_block: setup:launch_dynamics:state_arrays
% render_block: solver:launch_dynamics:loop_begin
% render_block: fragment:launch_dynamics:mass_depletion
% render_block: fragment:launch_dynamics:constant_thrust
% render_block: fragment:launch_dynamics:quadratic_drag_air
% render_block: fragment:launch_dynamics:gravity_scalar
% render_block: update:launch_dynamics:state
% render_block: solver:launch_dynamics:loop_end
% render_block: postprocess:launch_dynamics:metrics
% render_block: output:launch_dynamics:plots
% fragment: constant_thrust | library/native | equation_fragments | constant thrust term | F_thrust = T
% fragment: mass_depletion | library/native | equation_fragments | linear mass depletion during burn | m(t) = m0 - burn_rate * t
% fragment: quadratic_drag_air | library/native | equation_fragments | quadratic aerodynamic drag | F_drag = 0.5 * rho_air * Cd * A * v * abs(v)
% fragment: gravity_scalar | library/native | equation_fragments | scalar gravity term | F_gravity = m * g
% equation: dh/dt = v
% equation: m dv/dt = thrust - drag - m g

clear; clc; close all;

use_thrust = true;
use_mass_depletion = true;
use_drag = true;
use_gravity = true;

mass0 = 1200;
fuel_mass = 400;
burn_rate = 8;
thrust = 18000;
Cd = 0.4;
A = 1.2;
rho = 1.225;
g = 9.81;
dt = 0.1;
T = 20.0;

t = 0:dt:T;
N = numel(t);

h = zeros(N,1);
v = zeros(N,1);
a = zeros(N,1);
m = zeros(N,1);
m(1) = mass0;

for k = 2:N
    tk = t(k);

    if use_mass_depletion
        burned = min(fuel_mass, burn_rate * tk);
        m(k) = max(mass0 - burned, mass0 - fuel_mass);
    else
        burned = 0;
        m(k) = mass0;
    end

    if use_thrust
        if use_mass_depletion
            current_thrust = thrust * (burned < fuel_mass);
        else
            current_thrust = thrust;
        end
    else
        current_thrust = 0;
    end

    if use_drag
        drag = 0.5 * rho * Cd * A * v(max(k-1,1)) * abs(v(max(k-1,1)));
    else
        drag = 0;
    end

    if use_gravity
        weight = m(k) * g;
    else
        weight = 0;
    end

    a(k) = (current_thrust - drag - weight) / max(m(k), 1e-9);
    if k > 1
        v(k) = v(k-1) + a(k) * dt;
        h(k) = max(0, h(k-1) + v(k) * dt);
    end

end

[max_h, idx] = max(h);
fprintf('Max altitude: %.2f m at t = %.2f s\n', max_h, t(idx));
fprintf('Final velocity: %.2f m/s\n', v(end));

figure('Name', 'Launch Dynamics 1D');
subplot(3,1,1); plot(t, h, 'LineWidth', 1.6); grid on; ylabel('Altitude (m)'); title('IR-Block Launch Dynamics');
subplot(3,1,2); plot(t, v, 'LineWidth', 1.6); grid on; ylabel('Velocity (m/s)');
subplot(3,1,3); plot(t, a, 'LineWidth', 1.6); grid on; ylabel('Acceleration (m/s^2)'); xlabel('Time (s)');