%% Generated by RAG ModelSpec pipeline
% task_goal: 生成一个 template_family=orbital_dynamics 的轨道传播模型，高度400km，v0=7670m/s，仿真5400s，dt=10s
% model_id: satellite_orbit_2body
% generator_strategy: ir_composable_renderer
% template_family: orbital_dynamics
% governing_form: ode
% solver: discrete_euler
% codegen_strategy: ir_composable_renderer
% equation_fragments: two_body_gravity_planar
% render_blocks: meta:comments, workspace:clear, setup:orbital_dynamics:fragment_flags, declare:orbital_dynamics:parameters, setup:orbital_dynamics:time_grid, setup:orbital_dynamics:state_arrays, setup:orbital_dynamics:initial_conditions, solver:orbital_dynamics:loop_begin, fragment:orbital_dynamics:two_body_gravity_planar, update:orbital_dynamics:state, solver:orbital_dynamics:loop_end, postprocess:orbital_dynamics:metrics, output:orbital_dynamics:plots
% assumptions:
%   - 采用平面二体模型
%   - 忽略J2与摄动
% evidence:
%   - model=satellite_orbit_2body, score=12.0212, id=133
%   - model=, score=11.9337, id=200091
%   - model=, score=11.85, id=200094
%   - model=, score=11.85, id=200095
%   - model=, score=11.6099, id=200092
%% IR-block-composed MATLAB model: 2-Body Satellite Orbit
% family: orbital_dynamics
% governing_form: ode
% solver: discrete_euler
% codegen_strategy: ir_composable_renderer
% render_block: meta:comments
% render_block: workspace:clear
% render_block: setup:orbital_dynamics:fragment_flags
% render_block: declare:orbital_dynamics:parameters
% render_block: setup:orbital_dynamics:time_grid
% render_block: setup:orbital_dynamics:state_arrays
% render_block: setup:orbital_dynamics:initial_conditions
% render_block: solver:orbital_dynamics:loop_begin
% render_block: fragment:orbital_dynamics:two_body_gravity_planar
% render_block: update:orbital_dynamics:state
% render_block: solver:orbital_dynamics:loop_end
% render_block: postprocess:orbital_dynamics:metrics
% render_block: output:orbital_dynamics:plots
% fragment: two_body_gravity_planar | library/native | equation_fragments | planar two-body gravity | a = -mu * r / ||r||^3
% equation: dr/dt = v
% equation: dv/dt = -mu * r / ||r||^3

clear; clc; close all;

use_gravity = true;

mu = 398600000000000.0;
Re = 6371000.0;
altitude0 = 400000.0;
v0 = 7670.0;
dt = 10.0;
T = 5400.0;

t = 0:dt:T;
N = numel(t);

x = zeros(N,1);
y = zeros(N,1);
vx = zeros(N,1);
vy = zeros(N,1);

x(1) = Re + altitude0;
vy(1) = v0;

for k = 2:N
    r = max(hypot(x(k-1), y(k-1)), 1e-9);

    if use_gravity
        ax = -mu * x(k-1) / r^3;
        ay = -mu * y(k-1) / r^3;
    else
        ax = 0;
        ay = 0;
    end

    vx(k) = vx(k-1) + ax * dt;
    vy(k) = vy(k-1) + ay * dt;
    x(k) = x(k-1) + vx(k) * dt;
    y(k) = y(k-1) + vy(k) * dt;

end

radius = hypot(x, y);
altitude = radius - Re;
theta = linspace(0, 2*pi, 400);

figure('Name', 'Orbital Dynamics 2D');
subplot(1,2,1); fill(Re*cos(theta), Re*sin(theta), [0.7 0.85 1.0], 'EdgeColor', 'none'); hold on; plot(x, y, 'r', 'LineWidth', 1.6); axis equal; grid on; xlabel('X (m)'); ylabel('Y (m)'); title('IR-Block Orbit');
subplot(1,2,2); plot(t, altitude / 1e3, 'LineWidth', 1.6); grid on; xlabel('Time (s)'); ylabel('Altitude (km)'); title('Altitude Evolution');