%% Generated by RAG ModelSpec pipeline
% task_goal: 生成一个卫星低空轨道模型
% model_id: satellite_orbit_2body
% generator_strategy: template
% assumptions:
%   - 采用平面二体模型
%   - 忽略J2与摄动
% evidence:
%   - model=, score=1.0, id=web_research_1
%   - model=satellite_orbit_2body, score=9.77, id=133
%   - model=satellite_orbit_2body, score=7.9777, id=136
%   - model=satellite_orbit_2body, score=7.8866, id=135
%   - model=satellite_orbit_2body, score=7.3303, id=131
function [y, f] = satellite_orbit_2body(mode, time, Ts, x, u)
    mode_codes = local_builtin_msg_simu();
    INIT = mode_codes.SM_INITIALIZE;
    CONT = mode_codes.SM_CONTINUE;
    OUT  = mode_codes.SM_OUTPUT;
    EXIT = mode_codes.SM_STOP;

    mu = 398600000000000.0;
    Re = 6371000.0;

    state_dim = max(0, 4);
    output_dim = max(0, 3);
    input_dim = max(0, 0);

    if nargin < 4 || isempty(x)
        x = [6371000.0 + 400000.0; 0; 0; 10000.0];
    else
        x = x(:);
    end
    if state_dim == 0
        x = zeros(0, 1);
    elseif numel(x) < state_dim
        x = [x; zeros(state_dim - numel(x), 1)];
    elseif numel(x) > state_dim
        x = x(1:state_dim);
    end

    if nargin < 5 || isempty(u)
        u = zeros(0, 1);
    else
        u = u(:);
    end
    if input_dim == 0
        u = zeros(0, 1);
    elseif numel(u) < input_dim
        u = [u; zeros(input_dim - numel(u), 1)];
    elseif numel(u) > input_dim
        u = u(1:input_dim);
    end

    switch mode
        case INIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            pos_x = x(1);
            pos_y = x(2);
            vel_x = x(3);
            vel_y = x(4);
            radius = max(hypot(pos_x, pos_y), Re);
            ax_val = -mu * pos_x / radius^3;
            ay_val = -mu * pos_y / radius^3;
            altitude = radius - Re;
            speed = hypot(vel_x, vel_y);
            y(1) = pos_x;
            y(2) = pos_y;
            y(3) = altitude;
            f(1) = vel_x;
            f(2) = vel_y;
            f(3) = ax_val;
            f(4) = ay_val;

        case CONT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            pos_x = x(1);
            pos_y = x(2);
            vel_x = x(3);
            vel_y = x(4);
            radius = max(hypot(pos_x, pos_y), Re);
            ax_val = -mu * pos_x / radius^3;
            ay_val = -mu * pos_y / radius^3;
            altitude = radius - Re;
            speed = hypot(vel_x, vel_y);
            y(1) = pos_x;
            y(2) = pos_y;
            y(3) = altitude;
            f(1) = vel_x;
            f(2) = vel_y;
            f(3) = ax_val;
            f(4) = ay_val;

        case OUT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);
            pos_x = x(1);
            pos_y = x(2);
            vel_x = x(3);
            vel_y = x(4);
            radius = max(hypot(pos_x, pos_y), Re);
            ax_val = -mu * pos_x / radius^3;
            ay_val = -mu * pos_y / radius^3;
            altitude = radius - Re;
            speed = hypot(vel_x, vel_y);
            y(1) = pos_x;
            y(2) = pos_y;
            y(3) = altitude;

        case EXIT
            y = zeros(output_dim, 1);
            f = zeros(state_dim, 1);

        otherwise
            error('Invalid mode');
    end
end

function mode_codes = local_builtin_msg_simu()
    persistent cached_mode_codes;
    if isempty(cached_mode_codes)
        cached_mode_codes = struct();
        cached_mode_codes.SM_START = 10100;
        cached_mode_codes.SM_INFO = 10101;
        cached_mode_codes.SM_INITIALIZE = 10102;
        cached_mode_codes.SM_CONTINUE = 10103;
        cached_mode_codes.SM_STEPOVER = 10104;
        cached_mode_codes.SM_PAUSE = 10105;
        cached_mode_codes.SM_STOP = 10106;
        cached_mode_codes.SM_DEBUGMODEL = 10107;
        cached_mode_codes.SM_BULIDMODEL = 10108;
        cached_mode_codes.SM_STEPCHANGED = 10109;
        cached_mode_codes.SM_TIMEALIGN = 10110;
        cached_mode_codes.SM_WRITEDATA = 10111;
        cached_mode_codes.SM_USERMSG = 10112;
        cached_mode_codes.SM_BREAKPOINT = 10113;
        cached_mode_codes.SM_ERROR = 10114;
        cached_mode_codes.SM_CREATE = 10115;
        cached_mode_codes.SM_DESTROY = 10116;
        cached_mode_codes.SM_DRAW = 10117;
        cached_mode_codes.SM_WRITE = 10118;
        cached_mode_codes.SM_READ = 10119;
        cached_mode_codes.SM_RESTART = 10120;
        cached_mode_codes.SM_END = 10121;
        cached_mode_codes.SM_MONTE = 10122;
        cached_mode_codes.SM_STOPMODEL = 10123;
        cached_mode_codes.SM_OUTPUT = 10124;
        cached_mode_codes.SM_UPDATE = 10125;
        cached_mode_codes.SM_RENEW = 10126;
        cached_mode_codes.SM_SIMUMETHOD = 10127;
        cached_mode_codes.SM_STOPALL = 10128;
        cached_mode_codes.SM_SAVESNAP = 10129;
        cached_mode_codes.SM_LOADSNAP = 10130;
        cached_mode_codes.SM_NOACT = 10131;
        cached_mode_codes.SM_INITDATA = 10132;
    end
    mode_codes = cached_mode_codes;
end