%% Generated by RAG ModelSpec pipeline
% task_goal: 建立近地轨道卫星两体轨道模型，轨道高度400000，初始速度7670
% model_id: satellite_orbit_2body
% assumptions:
%   - 二维中心引力两体问题
%   - 忽略摄动与推力控制
% evidence:
%   - model=satellite_orbit_2body, score=17.0688, id=131
%   - model=satellite_orbit_2body, score=15.6679, id=132
%   - model=satellite_orbit_2body, score=9.1927, id=130
%   - model=satellite_orbit_2body, score=6.1457, id=133
%   - model=rocket_launch_1d, score=5.2509, id=100112
%% Auto-generated MATLAB model: 2-Body Satellite Orbit
clear; clc; close all;

mu = 398600000000000.0;
Re = 6371000.0;
altitude0 = 400000.0;
v0 = 7670.0;
dt = 5.0;
T = 5400.0;

t = 0:dt:T;
N = numel(t);
x = zeros(N,1);
y = zeros(N,1);
vx = zeros(N,1);
vy = zeros(N,1);

x(1) = Re + altitude0;
y(1) = 0;
vx(1) = 0;
vy(1) = v0;

for k = 2:N
    r = hypot(x(k-1), y(k-1));
    ax = -mu * x(k-1) / r^3;
    ay = -mu * y(k-1) / r^3;

    vx(k) = vx(k-1) + ax * dt;
    vy(k) = vy(k-1) + ay * dt;
    x(k) = x(k-1) + vx(k) * dt;
    y(k) = y(k-1) + vy(k) * dt;
end

radius = hypot(x, y);
altitude = radius - Re;
specific_energy = 0.5 * (vx.^2 + vy.^2) - mu ./ radius;
fprintf('Initial altitude: %.2f km
', altitude(1) / 1e3);
fprintf('Mean altitude: %.2f km
', mean(altitude) / 1e3);
fprintf('Specific orbital energy: %.3e J/kg
', mean(specific_energy));

theta = linspace(0, 2*pi, 400);
figure('Name', 'Satellite Orbit 2-Body');
subplot(1,2,1);
fill(Re*cos(theta), Re*sin(theta), [0.7 0.85 1.0], 'EdgeColor', 'none'); hold on;
plot(x, y, 'r', 'LineWidth', 1.6);
axis equal; grid on; xlabel('X (m)'); ylabel('Y (m)'); title('Planar Orbit'); legend('Earth', 'Satellite Orbit');
subplot(1,2,2);
plot(t, altitude / 1e3, 'LineWidth', 1.6); grid on; xlabel('Time (s)'); ylabel('Altitude (km)'); title('Altitude Evolution');
