%% Generated by RAG ModelSpec pipeline
% task_goal: 生成状态空间模型并进行仿真
% model_id: state_space_response
% assumptions:
%   - 用户提供的状态空间矩阵A、B、C、D符合模型要求
%   - 仿真时长为12秒
% evidence:
%   - model=transfer_function_step, score=7.4, id=2
%   - model=state_space_response, score=7.2, id=10
%   - model=state_space_response, score=6.0, id=11
%   - model=robot_2dof_kinematics, score=4.6, id=102
%   - model=battery_rc_model, score=4.3, id=80
%% Auto-generated MATLAB model: State Space Simulation
clear; clc; close all;

A = [0 1; -2 -3];
B = [0; 1];
C = [1 0];
D = [0];
sys = ss(A, B, C, D);

t = linspace(0, 12.0, 1000)';
u = ones(size(t));
y = lsim(sys, u, t);

figure('Name', 'State Space Output');
plot(t, y, 'LineWidth', 1.5);
xlabel('Time (s)');
ylabel('Output');
title('State Space Simulation');
grid on;
