%% Generated by RAG ModelSpec pipeline
% task_goal: 构建一个潜艇水下发射鱼雷模型，考虑水下阻力等因素
% model_id: torpedo_underwater_launch_1d
% assumptions:
%   - 使用默认参数补全未明确指定项
% evidence:
%   - model=torpedo_underwater_launch_1d, score=20.0, id=141
%   - model=torpedo_underwater_launch_1d, score=7.8139, id=142
%   - model=torpedo_underwater_launch_1d, score=7.4155, id=140
%   - model=rocket_launch_1d, score=5.602, id=100112
%   - model=torpedo_underwater_launch_1d, score=4.9872, id=143
%% Auto-generated MATLAB model: 1D Torpedo Underwater Launch
clear; clc; close all;

mass = 180.0;
thrust = 3200.0;
Cd = 0.35;
A = 0.045;
rho = 1000.0;
Vd = 0.16;
g = 9.81;
dt = 0.02;
T = 25.0;

t = 0:dt:T;
N = numel(t);
s = zeros(N,1);
v = zeros(N,1);
a = zeros(N,1);

weight = mass * g;
buoyancy = rho * g * Vd;

for k = 2:N
    drag = 0.5 * rho * Cd * A * v(k-1) * abs(v(k-1));
    net_force = thrust + buoyancy - weight - drag;
    a(k) = net_force / mass;
    v(k) = v(k-1) + a(k) * dt;
    s(k) = max(0, s(k-1) + v(k) * dt);
end

fprintf('Final displacement: %.2f m
', s(end));
fprintf('Peak speed: %.2f m/s
', max(v));
fprintf('Buoyancy minus weight: %.2f N
', buoyancy - weight);

figure('Name', 'Torpedo Underwater Launch 1D');
subplot(3,1,1); plot(t, s, 'LineWidth', 1.6); grid on; ylabel('Displacement (m)'); title('Underwater Launch Displacement');
subplot(3,1,2); plot(t, v, 'LineWidth', 1.6); grid on; ylabel('Velocity (m/s)');
subplot(3,1,3); plot(t, a, 'LineWidth', 1.6); grid on; ylabel('Acceleration (m/s^2)'); xlabel('Time (s)');
