%% Generated by RAG ModelSpec pipeline
% task_goal: 生成一个潜艇发射鱼雷模型，考虑水下阻力，障碍躲避等因素
% model_id: torpedo_underwater_launch_1d
% generator_strategy: ir_composable_renderer
% template_family: underwater_launch
% governing_form: ode
% solver: discrete_euler
% codegen_strategy: ir_composable_renderer
% equation_fragments: constant_thrust, quadratic_drag_water, gravity_scalar, buoyancy_scalar
% render_blocks: meta:comments, workspace:clear, setup:underwater_launch:fragment_flags, declare:underwater_launch:parameters, setup:underwater_launch:time_grid, setup:underwater_launch:state_arrays, fragment:underwater_launch:gravity_scalar, fragment:underwater_launch:buoyancy_scalar, solver:underwater_launch:loop_begin, fragment:underwater_launch:quadratic_drag_water, fragment:underwater_launch:constant_thrust, update:underwater_launch:state, solver:underwater_launch:loop_end, postprocess:underwater_launch:metrics, output:underwater_launch:plots
% assumptions:
%   - 一维发射轴方向运动
%   - 考虑推力、重力、浮力与二次阻力
% evidence:
%   - model=rocket_launch_1d, score=11.9004, id=111
%   - model=torpedo_underwater_launch_1d, score=9.8346, id=141
%   - model=torpedo_underwater_launch_1d, score=8.1678, id=140
%   - model=torpedo_underwater_launch_1d, score=7.7937, id=142
%   - model=rocket_launch_1d, score=6.046, id=112
%% IR-block-composed MATLAB model: 1D Torpedo Underwater Launch\n% family: underwater_launch
% governing_form: ode
% solver: discrete_euler
% codegen_strategy: ir_composable_renderer
% render_block: meta:comments
% render_block: workspace:clear
% render_block: setup:underwater_launch:fragment_flags
% render_block: declare:underwater_launch:parameters
% render_block: setup:underwater_launch:time_grid
% render_block: setup:underwater_launch:state_arrays
% render_block: fragment:underwater_launch:gravity_scalar
% render_block: fragment:underwater_launch:buoyancy_scalar
% render_block: solver:underwater_launch:loop_begin
% render_block: fragment:underwater_launch:quadratic_drag_water
% render_block: fragment:underwater_launch:constant_thrust
% render_block: update:underwater_launch:state
% render_block: solver:underwater_launch:loop_end
% render_block: postprocess:underwater_launch:metrics
% render_block: output:underwater_launch:plots
% fragment: constant_thrust | constant thrust term | F_thrust = T
% fragment: quadratic_drag_water | quadratic hydrodynamic drag | F_drag = 0.5 * rho_water * Cd * A * v * abs(v)
% fragment: gravity_scalar | scalar gravity term | F_gravity = m * g
% fragment: buoyancy_scalar | buoyancy term | F_buoyancy = rho * g * V_disp
% equation: ds/dt = v
% equation: m dv/dt = thrust + buoyancy - drag - m g

clear; clc; close all;

use_thrust = true;\nuse_drag = true;\nuse_gravity = true;\nuse_buoyancy = true;

mass = 180.0;\nthrust = 3200.0;\nCd = 0.35;\nA = 0.045;\nrho = 1000.0;\nVd = 0.16;\ng = 9.81;\ndt = 0.02;\nT = 25.0;

t = 0:dt:T;\nN = numel(t);

s = zeros(N,1);\nv = zeros(N,1);\na = zeros(N,1);

if use_gravity\n    weight = mass * g;\nelse\n    weight = 0;\nend

if use_buoyancy\n    buoyancy = rho * g * Vd;\nelse\n    buoyancy = 0;\nend

for k = 2:N

    if use_drag\n        drag = 0.5 * rho * Cd * A * v(k-1) * abs(v(k-1));\n    else\n        drag = 0;\n    end

    if use_thrust\n        current_thrust = thrust;\n    else\n        current_thrust = 0;\n    end

    net_force = current_thrust + buoyancy - weight - drag;\n    a(k) = net_force / max(mass, 1e-9);\n    v(k) = v(k-1) + a(k) * dt;\n    s(k) = max(0, s(k-1) + v(k) * dt);

end

fprintf('Final displacement: %.2f m\n', s(end));\nfprintf('Peak speed: %.2f m/s\n', max(v));

figure('Name', 'Underwater Launch 1D');\nsubplot(3,1,1); plot(t, s, 'LineWidth', 1.6); grid on; ylabel('Displacement (m)'); title('IR-Block Underwater Launch');\nsubplot(3,1,2); plot(t, v, 'LineWidth', 1.6); grid on; ylabel('Velocity (m/s)');\nsubplot(3,1,3); plot(t, a, 'LineWidth', 1.6); grid on; ylabel('Acceleration (m/s^2)'); xlabel('Time (s)');