%% Generated by RAG ModelSpec pipeline
% task_goal: 构建一个潜艇水下发射鱼雷模型，忽略水下阻力，但保留浮力，质量=180，推力=3200，阻力系数=0.35
% model_id: torpedo_underwater_launch_1d
% generator_strategy: ir_composable_renderer
% template_family: underwater_launch
% governing_form: ode
% solver: discrete_euler
% codegen_strategy: ir_composable_renderer
% equation_fragments: constant_thrust, gravity_scalar, buoyancy_scalar
% render_blocks: script_preamble, parameter_declarations, state_initialization, solver:discrete_euler, fragment:constant_thrust, fragment:gravity_scalar, fragment:buoyancy_scalar, output:plot, output:displacement, output:velocity, output:acceleration
% assumptions:
%   - 一维发射轴方向运动
%   - 考虑推力、重力、浮力与二次阻力
% evidence:
%   - model=torpedo_underwater_launch_1d, score=17.35, id=141
%   - model=torpedo_underwater_launch_1d, score=8.0352, id=140
%   - model=torpedo_underwater_launch_1d, score=7.67, id=142
%% Family-assembled MATLAB model: 1D underwater launch
% family: underwater_launch
% governing_form: ode
% solver: discrete_euler
% codegen_strategy: ir_composable_renderer
% render_block: script_preamble
% render_block: parameter_declarations
% render_block: state_initialization
% render_block: solver:discrete_euler
% render_block: fragment:constant_thrust
% render_block: fragment:gravity_scalar
% render_block: fragment:buoyancy_scalar
% render_block: output:plot
% render_block: output:displacement
% render_block: output:velocity
% render_block: output:acceleration
% fragment: constant_thrust | constant thrust term | F_thrust = T
% fragment: gravity_scalar | scalar gravity term | F_gravity = m * g
% fragment: buoyancy_scalar | buoyancy term | F_buoyancy = rho * g * V_disp
% equation: ds/dt = v
% equation: m dv/dt = thrust + buoyancy - m g
clear; clc; close all;

use_thrust = true;
use_drag = false;
use_gravity = true;
use_buoyancy = true;

mass = 180.0;
thrust = 3200.0;
Cd = 0.35;
A = 0.045;
rho = 1000.0;
Vd = 0.16;
g = 9.81;
dt = 0.02;
T = 25.0;

t = 0:dt:T;
N = numel(t);
s = zeros(N,1);
v = zeros(N,1);
a = zeros(N,1);

if use_gravity
    weight = mass * g;
else
    weight = 0;
end
if use_buoyancy
    buoyancy = rho * g * Vd;
else
    buoyancy = 0;
end
for k = 2:N
    if use_drag
        drag = 0.5 * rho * Cd * A * v(k-1) * abs(v(k-1));
    else
        drag = 0;
    end
    if use_thrust
        current_thrust = thrust;
    else
        current_thrust = 0;
    end
    net_force = current_thrust + buoyancy - weight - drag;
    a(k) = net_force / max(mass, 1e-9);
    v(k) = v(k-1) + a(k) * dt;
    s(k) = max(0, s(k-1) + v(k) * dt);
end

fprintf('Final displacement: %.2f m
', s(end));
fprintf('Peak speed: %.2f m/s
', max(v));

figure('Name', 'Underwater Launch 1D');
subplot(3,1,1); plot(t, s, 'LineWidth', 1.6); grid on; ylabel('Displacement (m)'); title('Family-Assembled Underwater Launch');
subplot(3,1,2); plot(t, v, 'LineWidth', 1.6); grid on; ylabel('Velocity (m/s)');
subplot(3,1,3); plot(t, a, 'LineWidth', 1.6); grid on; ylabel('Acceleration (m/s^2)'); xlabel('Time (s)');
