%% Generated by RAG ModelSpec pipeline
% task_goal: ???????????????????????????
% model_id: underwater_launch_constant_thrust_buoyancy_scalar
% generator_strategy: ir_composable_renderer
% template_family: underwater_launch
% governing_form: ode
% solver: discrete_euler
% codegen_strategy: ir_composable_renderer
% equation_fragments: constant_thrust, buoyancy_scalar, gravity_scalar
% render_blocks: meta:comments, workspace:clear, setup:underwater_launch:fragment_flags, declare:underwater_launch:parameters, setup:underwater_launch:time_grid, setup:underwater_launch:state_arrays, fragment:underwater_launch:gravity_scalar, fragment:underwater_launch:buoyancy_scalar, solver:underwater_launch:loop_begin, fragment:underwater_launch:quadratic_drag_water, fragment:underwater_launch:constant_thrust, update:underwater_launch:state, solver:underwater_launch:loop_end, postprocess:underwater_launch:metrics, output:underwater_launch:plots
%% IR-block-composed MATLAB model: Torpedo Underwater Launch
% family: underwater_launch
% governing_form: ode
% solver: discrete_euler
% codegen_strategy: ir_composable_renderer
% render_block: meta:comments
% render_block: workspace:clear
% render_block: setup:underwater_launch:fragment_flags
% render_block: declare:underwater_launch:parameters
% render_block: setup:underwater_launch:time_grid
% render_block: setup:underwater_launch:state_arrays
% render_block: fragment:underwater_launch:gravity_scalar
% render_block: fragment:underwater_launch:buoyancy_scalar
% render_block: solver:underwater_launch:loop_begin
% render_block: fragment:underwater_launch:quadratic_drag_water
% render_block: fragment:underwater_launch:constant_thrust
% render_block: update:underwater_launch:state
% render_block: solver:underwater_launch:loop_end
% render_block: postprocess:underwater_launch:metrics
% render_block: output:underwater_launch:plots
% fragment: constant_thrust | constant thrust term | F_thrust = T
% fragment: buoyancy_scalar | buoyancy term | F_buoyancy = rho * g * V_disp
% fragment: gravity_scalar | scalar gravity term | F_gravity = m * g
% equation: ds/dt = v
% equation: m dv/dt = thrust + buoyancy - m g

clear; clc; close all;

use_thrust = true;
use_drag = false;
use_gravity = true;
use_buoyancy = true;

mass = 180;
thrust = 3200;
Cd = 0.35;
A = 0.045;
rho = 1000.0;
Vd = 0.16;
g = 9.81;
dt = 0.02;
T = 20;

t = 0:dt:T;
N = numel(t);

s = zeros(N,1);
v = zeros(N,1);
a = zeros(N,1);

if use_gravity
    weight = mass * g;
else
    weight = 0;
end

if use_buoyancy
    buoyancy = rho * g * Vd;
else
    buoyancy = 0;
end

for k = 2:N

    if use_drag
        drag = 0.5 * rho * Cd * A * v(k-1) * abs(v(k-1));
    else
        drag = 0;
    end

    if use_thrust
        current_thrust = thrust;
    else
        current_thrust = 0;
    end

    net_force = current_thrust + buoyancy - weight - drag;
    a(k) = net_force / max(mass, 1e-9);
    v(k) = v(k-1) + a(k) * dt;
    s(k) = max(0, s(k-1) + v(k) * dt);

end

fprintf('Final displacement: %.2f m
', s(end));
fprintf('Peak speed: %.2f m/s
', max(v));

figure('Name', 'Underwater Launch 1D');
subplot(3,1,1); plot(t, s, 'LineWidth', 1.6); grid on; ylabel('Displacement (m)'); title('IR-Block Underwater Launch');
subplot(3,1,2); plot(t, v, 'LineWidth', 1.6); grid on; ylabel('Velocity (m/s)');
subplot(3,1,3); plot(t, a, 'LineWidth', 1.6); grid on; ylabel('Acceleration (m/s^2)'); xlabel('Time (s)');