"""
Generate MATLAB script from validated ModelSpec.
"""

from __future__ import annotations

from typing import Any, Dict, List

from knowledge_base.matlab_generator import MatlabModelGenerator


class MatlabCodeGenerator:
    def __init__(self):
        self.generator = MatlabModelGenerator()

    def generate_from_spec(
        self,
        spec: Dict[str, Any],
        evidence_docs: List[Dict[str, Any]] | None = None,
        output_dir: str = "generated_models",
    ) -> Dict[str, Any]:
        model_id = spec.get("model_id")
        if not model_id:
            return {"status": "error", "message": "spec.model_id is required"}

        params = dict(spec.get("parameters", {}))
        simulation_plan = spec.get("simulation_plan", {})
        if isinstance(simulation_plan, dict) and "stop_time" in simulation_plan:
            params["stop_time"] = simulation_plan["stop_time"]

        try:
            core_script = self.generator.render_script(model_id, params)
        except Exception as exc:
            return {"status": "error", "message": f"render failed: {exc}"}

        header = self._build_header(spec, evidence_docs or [])
        script = header + "\n" + core_script

        try:
            file_name, file_path = self.generator.save_script(
                code=script,
                model_id=model_id,
                output_dir=output_dir,
            )
        except Exception as exc:
            return {"status": "error", "message": f"save failed: {exc}"}

        return {
            "status": "success",
            "model_id": model_id,
            "model_name": self._resolve_model_name(model_id),
            "file_name": file_name,
            "file_path": file_path,
            "script": script,
            "spec": spec,
        }

    def _resolve_model_name(self, model_id: str) -> str:
        for item in self.generator.catalog:
            if item.get("model_id") == model_id:
                return item.get("name", model_id)
        return model_id

    def _build_header(self, spec: Dict[str, Any], evidence_docs: List[Dict[str, Any]]) -> str:
        lines = [
            "%% Generated by RAG ModelSpec pipeline",
            f"% task_goal: {spec.get('task_goal', '')}",
            f"% model_id: {spec.get('model_id', '')}",
        ]
        assumptions = spec.get("assumptions", [])
        if assumptions:
            lines.append("% assumptions:")
            for item in assumptions[:6]:
                lines.append(f"%   - {item}")

        if evidence_docs:
            lines.append("% evidence:")
            for e in evidence_docs[:5]:
                payload = e.get("payload", {})
                lines.append(
                    f"%   - model={payload.get('model_id', '')}, score={e.get('score', 0)}, id={e.get('id', '')}"
                )
        return "\n".join(lines)

