"""Aggregated MATLAB IR block registry and family render rules."""

from __future__ import annotations

from typing import Dict, List

from .aerospace import (
    BLOCK_LIBRARY as AEROSPACE_BLOCK_LIBRARY,
    FAMILY_RENDER_RULES as AEROSPACE_FAMILY_RENDER_RULES,
    FRAGMENT_FLAG_RULES as AEROSPACE_FRAGMENT_FLAG_RULES,
    FRAGMENT_RENDER_ORDER as AEROSPACE_FRAGMENT_RENDER_ORDER,
    PARAMETER_DECLARATION_RULES as AEROSPACE_PARAMETER_DECLARATION_RULES,
)
from .battlefield import (
    BLOCK_LIBRARY as BATTLEFIELD_BLOCK_LIBRARY,
    FAMILY_RENDER_RULES as BATTLEFIELD_FAMILY_RENDER_RULES,
    FRAGMENT_FLAG_RULES as BATTLEFIELD_FRAGMENT_FLAG_RULES,
    FRAGMENT_RENDER_ORDER as BATTLEFIELD_FRAGMENT_RENDER_ORDER,
    PARAMETER_DECLARATION_RULES as BATTLEFIELD_PARAMETER_DECLARATION_RULES,
)
from .common import (
    BLOCK_LIBRARY as COMMON_BLOCK_LIBRARY,
    BlockRenderer,
    DEFAULT_RENDER_RULE,
    RenderRuleToken,
    _family_block_id,
    _fragment_group,
)
from .orbital import (
    BLOCK_LIBRARY as ORBITAL_BLOCK_LIBRARY,
    FAMILY_RENDER_RULES as ORBITAL_FAMILY_RENDER_RULES,
    FRAGMENT_FLAG_RULES as ORBITAL_FRAGMENT_FLAG_RULES,
    FRAGMENT_RENDER_ORDER as ORBITAL_FRAGMENT_RENDER_ORDER,
    PARAMETER_DECLARATION_RULES as ORBITAL_PARAMETER_DECLARATION_RULES,
)
from .tracking import (
    BLOCK_LIBRARY as TRACKING_BLOCK_LIBRARY,
    FAMILY_RENDER_RULES as TRACKING_FAMILY_RENDER_RULES,
    FRAGMENT_FLAG_RULES as TRACKING_FRAGMENT_FLAG_RULES,
    FRAGMENT_RENDER_ORDER as TRACKING_FRAGMENT_RENDER_ORDER,
    PARAMETER_DECLARATION_RULES as TRACKING_PARAMETER_DECLARATION_RULES,
)
from .underwater import (
    BLOCK_LIBRARY as UNDERWATER_BLOCK_LIBRARY,
    FAMILY_RENDER_RULES as UNDERWATER_FAMILY_RENDER_RULES,
    FRAGMENT_FLAG_RULES as UNDERWATER_FRAGMENT_FLAG_RULES,
    FRAGMENT_RENDER_ORDER as UNDERWATER_FRAGMENT_RENDER_ORDER,
    PARAMETER_DECLARATION_RULES as UNDERWATER_PARAMETER_DECLARATION_RULES,
)

BLOCK_LIBRARY: Dict[str, BlockRenderer] = {}
BLOCK_LIBRARY.update(COMMON_BLOCK_LIBRARY)
BLOCK_LIBRARY.update(AEROSPACE_BLOCK_LIBRARY)
BLOCK_LIBRARY.update(UNDERWATER_BLOCK_LIBRARY)
BLOCK_LIBRARY.update(ORBITAL_BLOCK_LIBRARY)
BLOCK_LIBRARY.update(TRACKING_BLOCK_LIBRARY)
BLOCK_LIBRARY.update(BATTLEFIELD_BLOCK_LIBRARY)

FRAGMENT_RENDER_ORDER: Dict[str, List[str]] = {}
FRAGMENT_RENDER_ORDER.update(AEROSPACE_FRAGMENT_RENDER_ORDER)
FRAGMENT_RENDER_ORDER.update(UNDERWATER_FRAGMENT_RENDER_ORDER)
FRAGMENT_RENDER_ORDER.update(ORBITAL_FRAGMENT_RENDER_ORDER)
FRAGMENT_RENDER_ORDER.update(TRACKING_FRAGMENT_RENDER_ORDER)
FRAGMENT_RENDER_ORDER.update(BATTLEFIELD_FRAGMENT_RENDER_ORDER)

FRAGMENT_FLAG_RULES: Dict[str, List[tuple[str, str]]] = {}
FRAGMENT_FLAG_RULES.update(AEROSPACE_FRAGMENT_FLAG_RULES)
FRAGMENT_FLAG_RULES.update(UNDERWATER_FRAGMENT_FLAG_RULES)
FRAGMENT_FLAG_RULES.update(ORBITAL_FRAGMENT_FLAG_RULES)
FRAGMENT_FLAG_RULES.update(TRACKING_FRAGMENT_FLAG_RULES)
FRAGMENT_FLAG_RULES.update(BATTLEFIELD_FRAGMENT_FLAG_RULES)

PARAMETER_DECLARATION_RULES: Dict[str, List[tuple[str, str, str | None]]] = {}
PARAMETER_DECLARATION_RULES.update(AEROSPACE_PARAMETER_DECLARATION_RULES)
PARAMETER_DECLARATION_RULES.update(UNDERWATER_PARAMETER_DECLARATION_RULES)
PARAMETER_DECLARATION_RULES.update(ORBITAL_PARAMETER_DECLARATION_RULES)
PARAMETER_DECLARATION_RULES.update(TRACKING_PARAMETER_DECLARATION_RULES)
PARAMETER_DECLARATION_RULES.update(BATTLEFIELD_PARAMETER_DECLARATION_RULES)

FAMILY_RENDER_RULES: Dict[str, List[RenderRuleToken]] = {}
FAMILY_RENDER_RULES.update(AEROSPACE_FAMILY_RENDER_RULES)
FAMILY_RENDER_RULES.update(UNDERWATER_FAMILY_RENDER_RULES)
FAMILY_RENDER_RULES.update(ORBITAL_FAMILY_RENDER_RULES)
FAMILY_RENDER_RULES.update(TRACKING_FAMILY_RENDER_RULES)
FAMILY_RENDER_RULES.update(BATTLEFIELD_FAMILY_RENDER_RULES)

DOMAIN_FAMILY_SPECTRUM: Dict[str, List[str]] = {
    "aerospace": sorted(AEROSPACE_FAMILY_RENDER_RULES.keys()),
    "underwater": sorted(UNDERWATER_FAMILY_RENDER_RULES.keys()),
    "orbital": sorted(ORBITAL_FAMILY_RENDER_RULES.keys()),
    "tracking": sorted(TRACKING_FAMILY_RENDER_RULES.keys()),
    "battlefield": sorted(BATTLEFIELD_FAMILY_RENDER_RULES.keys()),
}
ALL_REGISTERED_FAMILIES: List[str] = sorted(FAMILY_RENDER_RULES.keys())

__all__ = [
    'ALL_REGISTERED_FAMILIES',
    'BLOCK_LIBRARY',
    'DEFAULT_RENDER_RULE',
    'DOMAIN_FAMILY_SPECTRUM',
    'FAMILY_RENDER_RULES',
    'FRAGMENT_FLAG_RULES',
    'FRAGMENT_RENDER_ORDER',
    'PARAMETER_DECLARATION_RULES',
    'BlockRenderer',
    'RenderRuleToken',
    '_family_block_id',
    '_fragment_group',
]
