"""Aerospace-oriented MATLAB block rules and registrations."""

from __future__ import annotations

from typing import Dict, List

from .common import (
    BlockRenderer,
    RenderRuleToken,
    _family_block_id,
    _join_lines,
    _make_fragment_flag_renderer,
    _make_parameter_renderer,
    _register_block,
    _register_text_block,
    _standard_family_rule,
)

BLOCK_LIBRARY: Dict[str, BlockRenderer] = {}

FRAGMENT_RENDER_ORDER: Dict[str, List[str]] = {
    "launch_dynamics": ["mass_depletion", "constant_thrust", "quadratic_drag_air", "gravity_scalar"],
    "trajectory_ode": ["constant_thrust_vector", "quadratic_drag_planar", "gravity_planar"],
    "powered_ascent": ["mass_depletion", "pitch_program", "constant_thrust_vector", "quadratic_drag_planar", "gravity_planar"],
    "reentry_dynamics": ["atmosphere_density_decay", "gravity_planar", "quadratic_drag_planar", "lift_to_drag_planar", "heating_rate_proxy"],
    "aircraft_point_mass": ["thrust_drag_balance", "lift_balance", "bank_turn_rate"],
    "interceptor_guidance": ["constant_speed_target", "closing_velocity", "proportional_navigation"],
}

FRAGMENT_FLAG_RULES: Dict[str, List[tuple[str, str]]] = {
    "launch_dynamics": [
        ("use_thrust", "constant_thrust"),
        ("use_mass_depletion", "mass_depletion"),
        ("use_drag", "quadratic_drag_air"),
        ("use_gravity", "gravity_scalar"),
    ],
    "trajectory_ode": [
        ("use_thrust", "constant_thrust_vector"),
        ("use_drag", "quadratic_drag_planar"),
        ("use_gravity", "gravity_planar"),
    ],
    "powered_ascent": [
        ("use_mass_depletion", "mass_depletion"),
        ("use_pitch_program", "pitch_program"),
        ("use_thrust", "constant_thrust_vector"),
        ("use_drag", "quadratic_drag_planar"),
        ("use_gravity", "gravity_planar"),
    ],
    "reentry_dynamics": [
        ("use_atmosphere", "atmosphere_density_decay"),
        ("use_gravity", "gravity_planar"),
        ("use_drag", "quadratic_drag_planar"),
        ("use_lift", "lift_to_drag_planar"),
        ("use_heating", "heating_rate_proxy"),
    ],
    "aircraft_point_mass": [
        ("use_force_balance", "thrust_drag_balance"),
        ("use_lift", "lift_balance"),
        ("use_bank", "bank_turn_rate"),
    ],
    "interceptor_guidance": [
        ("use_target_motion", "constant_speed_target"),
        ("use_closing_velocity", "closing_velocity"),
        ("use_guidance", "proportional_navigation"),
    ],
}

PARAMETER_DECLARATION_RULES: Dict[str, List[tuple[str, str, str | None]]] = {
    "launch_dynamics": [
        ("mass0", "mass0", None),
        ("fuel_mass", "fuel_mass", None),
        ("burn_rate", "burn_rate", None),
        ("thrust", "thrust", None),
        ("Cd", "drag_coeff", None),
        ("A", "area", None),
        ("rho", "air_density", None),
        ("g", "g", None),
        ("dt", "dt", None),
        ("T", "stop_time", None),
    ],
    "trajectory_ode": [
        ("mass0", "mass0", None),
        ("thrust", "thrust", None),
        ("Cd", "drag_coeff", None),
        ("A", "area", None),
        ("rho", "air_density", None),
        ("g", "g", None),
        ("launch_angle_deg", "launch_angle_deg", None),
        ("init_speed", "init_speed", None),
        ("burn_time", "burn_time", None),
        ("dt", "dt", None),
        ("T", "stop_time", None),
    ],
    "powered_ascent": [
        ("mass0", "mass0", None),
        ("fuel_mass", "fuel_mass", None),
        ("burn_rate", "burn_rate", None),
        ("thrust", "thrust", None),
        ("Cd", "drag_coeff", None),
        ("A", "area", None),
        ("rho", "air_density", None),
        ("g", "g", None),
        ("init_speed", "init_speed", None),
        ("init_flight_path_deg", "init_flight_path_deg", None),
        ("pitch_start_deg", "pitch_start_deg", None),
        ("pitch_end_deg", "pitch_end_deg", None),
        ("pitch_ramp_time", "pitch_ramp_time", None),
        ("dt", "dt", None),
        ("T", "stop_time", None),
    ],
    "reentry_dynamics": [
        ("mass0", "mass0", None),
        ("Cd", "drag_coeff", None),
        ("A", "area", None),
        ("air_density_ref", "air_density_ref", None),
        ("scale_height", "scale_height", None),
        ("lift_to_drag", "lift_to_drag", None),
        ("g", "g", None),
        ("init_altitude", "init_altitude", None),
        ("init_speed", "init_speed", None),
        ("entry_angle_deg", "entry_angle_deg", None),
        ("dt", "dt", None),
        ("T", "stop_time", None),
    ],
    "aircraft_point_mass": [
        ("mass", "mass", None),
        ("thrust", "thrust", None),
        ("Cd", "drag_coeff", None),
        ("A", "area", None),
        ("wing_area", "wing_area", None),
        ("air_density", "air_density", None),
        ("lift_coeff", "lift_coeff", None),
        ("g", "g", None),
        ("bank_angle_deg", "bank_angle_deg", None),
        ("climb_cmd_deg", "climb_cmd_deg", None),
        ("init_speed", "init_speed", None),
        ("init_altitude", "init_altitude", None),
        ("dt", "dt", None),
        ("T", "stop_time", None),
    ],
    "interceptor_guidance": [
        ("missile_speed", "missile_speed", None),
        ("target_speed", "target_speed", None),
        ("target_heading_deg", "target_heading_deg", None),
        ("nav_gain", "nav_gain", None),
        ("init_range", "init_range", None),
        ("init_los_deg", "init_los_deg", None),
        ("dt", "dt", None),
        ("T", "stop_time", None),
    ],
}

FAMILY_RENDER_RULES: Dict[str, List[RenderRuleToken]] = {
    "launch_dynamics": _standard_family_rule(
        "launch_dynamics",
        setup_blocks=["time_grid", "state_arrays"],
        post_fragment_update_blocks=["state"],
    ),
    "trajectory_ode": _standard_family_rule(
        "trajectory_ode",
        setup_blocks=["time_grid", "state_arrays", "initial_conditions"],
        post_fragment_update_blocks=["state"],
        include_postprocess=False,
    ),
    "powered_ascent": _standard_family_rule(
        "powered_ascent",
        setup_blocks=["time_grid", "state_arrays", "initial_conditions"],
        post_fragment_update_blocks=["state"],
    ),
    "reentry_dynamics": _standard_family_rule(
        "reentry_dynamics",
        setup_blocks=["time_grid", "state_arrays", "initial_conditions"],
        post_fragment_update_blocks=["state"],
    ),
    "aircraft_point_mass": _standard_family_rule(
        "aircraft_point_mass",
        setup_blocks=["time_grid", "state_arrays", "initial_conditions"],
        post_fragment_update_blocks=["state"],
    ),
    "interceptor_guidance": _standard_family_rule(
        "interceptor_guidance",
        setup_blocks=["time_grid", "state_arrays", "initial_conditions"],
        post_fragment_update_blocks=["state"],
    ),
}

for family_name, flag_rules in FRAGMENT_FLAG_RULES.items():
    _register_block(
        BLOCK_LIBRARY,
        _family_block_id("setup", family_name, "fragment_flags"),
        _make_fragment_flag_renderer(family_name, flag_rules),
    )

for family_name, declaration_rules in PARAMETER_DECLARATION_RULES.items():
    _register_block(
        BLOCK_LIBRARY,
        _family_block_id("declare", family_name, "parameters"),
        _make_parameter_renderer(declaration_rules),
    )

STATIC_BLOCKS = {
    _family_block_id("setup", "launch_dynamics", "time_grid"): _join_lines(["t = 0:dt:T;", "N = numel(t);"]),
    _family_block_id("setup", "launch_dynamics", "state_arrays"): _join_lines(["h = zeros(N,1);", "v = zeros(N,1);", "a = zeros(N,1);", "m = zeros(N,1);", "m(1) = mass0;"]),
    _family_block_id("setup", "trajectory_ode", "time_grid"): _join_lines(["t = 0:dt:T;", "N = numel(t);"]),
    _family_block_id("setup", "trajectory_ode", "state_arrays"): _join_lines([
        "x = zeros(N,1);",
        "y = zeros(N,1);",
        "vx = zeros(N,1);",
        "vy = zeros(N,1);",
        "ax = zeros(N,1);",
        "ay = zeros(N,1);",
    ]),
    _family_block_id("setup", "trajectory_ode", "initial_conditions"): _join_lines([
        "theta = deg2rad(launch_angle_deg);",
        "vx(1) = init_speed * cos(theta);",
        "vy(1) = init_speed * sin(theta);",
    ]),
    _family_block_id("setup", "powered_ascent", "time_grid"): _join_lines(["t = 0:dt:T;", "N = numel(t);"]),
    _family_block_id("setup", "powered_ascent", "state_arrays"): _join_lines([
        "x = zeros(N,1);",
        "y = zeros(N,1);",
        "vx = zeros(N,1);",
        "vy = zeros(N,1);",
        "mass = zeros(N,1);",
        "flight_path_deg = zeros(N,1);",
    ]),
    _family_block_id("setup", "powered_ascent", "initial_conditions"): _join_lines([
        "gamma0 = deg2rad(init_flight_path_deg);",
        "vx(1) = init_speed * cos(gamma0);",
        "vy(1) = init_speed * sin(gamma0);",
        "mass(1) = mass0;",
        "flight_path_deg(1) = init_flight_path_deg;",
    ]),
    _family_block_id("setup", "reentry_dynamics", "time_grid"): _join_lines(["t = 0:dt:T;", "N = numel(t);"]),
    _family_block_id("setup", "reentry_dynamics", "state_arrays"): _join_lines([
        "x = zeros(N,1);",
        "y = zeros(N,1);",
        "vx = zeros(N,1);",
        "vy = zeros(N,1);",
        "heat_load = zeros(N,1);",
    ]),
    _family_block_id("setup", "reentry_dynamics", "initial_conditions"): _join_lines([
        "gamma0 = -deg2rad(abs(entry_angle_deg));",
        "y(1) = init_altitude;",
        "vx(1) = init_speed * cos(gamma0);",
        "vy(1) = init_speed * sin(gamma0);",
    ]),
    _family_block_id("setup", "aircraft_point_mass", "time_grid"): _join_lines(["t = 0:dt:T;", "N = numel(t);"]),
    _family_block_id("setup", "aircraft_point_mass", "state_arrays"): _join_lines([
        "x = zeros(N,1);",
        "y = zeros(N,1);",
        "v = zeros(N,1);",
        "gamma = zeros(N,1);",
        "heading = zeros(N,1);",
    ]),
    _family_block_id("setup", "aircraft_point_mass", "initial_conditions"): _join_lines([
        "y(1) = init_altitude;",
        "v(1) = init_speed;",
        "gamma(1) = deg2rad(climb_cmd_deg);",
        "heading(1) = 0;",
    ]),
    _family_block_id("setup", "interceptor_guidance", "time_grid"): _join_lines(["t = 0:dt:T;", "N = numel(t);"]),
    _family_block_id("setup", "interceptor_guidance", "state_arrays"): _join_lines([
        "missile_x = zeros(N,1);",
        "missile_y = zeros(N,1);",
        "target_x = zeros(N,1);",
        "target_y = zeros(N,1);",
        "missile_heading = zeros(N,1);",
        "miss_distance = zeros(N,1);",
    ]),
    _family_block_id("setup", "interceptor_guidance", "initial_conditions"): _join_lines([
        "los0 = deg2rad(init_los_deg);",
        "missile_heading(1) = los0;",
        "target_x(1) = init_range * cos(los0);",
        "target_y(1) = init_range * sin(los0);",
        "prev_los = los0;",
        "miss_distance(1) = hypot(target_x(1) - missile_x(1), target_y(1) - missile_y(1));",
    ]),
    _family_block_id("solver", "launch_dynamics", "loop_begin"): _join_lines(["for k = 2:N", "    tk = t(k);"]),
    _family_block_id("solver", "launch_dynamics", "loop_end"): "end",
    _family_block_id("solver", "trajectory_ode", "loop_begin"): _join_lines(["for k = 2:N", "    speed = hypot(vx(k-1), vy(k-1));"]),
    _family_block_id("solver", "trajectory_ode", "loop_end"): "end",
    _family_block_id("solver", "powered_ascent", "loop_begin"): _join_lines(["for k = 2:N", "    speed = max(hypot(vx(k-1), vy(k-1)), 1e-8);"]),
    _family_block_id("solver", "powered_ascent", "loop_end"): "end",
    _family_block_id("solver", "reentry_dynamics", "loop_begin"): _join_lines(["for k = 2:N", "    speed = max(hypot(vx(k-1), vy(k-1)), 1e-8);"]),
    _family_block_id("solver", "reentry_dynamics", "loop_end"): "end",
    _family_block_id("solver", "aircraft_point_mass", "loop_begin"): "for k = 2:N",
    _family_block_id("solver", "aircraft_point_mass", "loop_end"): "end",
    _family_block_id("solver", "interceptor_guidance", "loop_begin"): "for k = 2:N",
    _family_block_id("solver", "interceptor_guidance", "loop_end"): "end",
    _family_block_id("fragment", "launch_dynamics", "mass_depletion"): _join_lines([
        "    if use_mass_depletion",
        "        burned = min(fuel_mass, burn_rate * tk);",
        "        m(k) = max(mass0 - burned, mass0 - fuel_mass);",
        "    else",
        "        burned = 0;",
        "        m(k) = mass0;",
        "    end",
    ]),
    _family_block_id("fragment", "launch_dynamics", "constant_thrust"): _join_lines([
        "    if use_thrust",
        "        if use_mass_depletion",
        "            current_thrust = thrust * (burned < fuel_mass);",
        "        else",
        "            current_thrust = thrust;",
        "        end",
        "    else",
        "        current_thrust = 0;",
        "    end",
    ]),
    _family_block_id("fragment", "launch_dynamics", "quadratic_drag_air"): _join_lines([
        "    if use_drag",
        "        drag = 0.5 * rho * Cd * A * v(max(k-1,1)) * abs(v(max(k-1,1)));",
        "    else",
        "        drag = 0;",
        "    end",
    ]),
    _family_block_id("fragment", "launch_dynamics", "gravity_scalar"): _join_lines([
        "    if use_gravity",
        "        weight = m(k) * g;",
        "    else",
        "        weight = 0;",
        "    end",
    ]),
    _family_block_id("fragment", "trajectory_ode", "constant_thrust_vector"): _join_lines([
        "    if use_thrust",
        "        current_thrust = thrust * (t(k-1) <= burn_time);",
        "        thrust_x = current_thrust * cos(theta);",
        "        thrust_y = current_thrust * sin(theta);",
        "    else",
        "        thrust_x = 0;",
        "        thrust_y = 0;",
        "    end",
    ]),
    _family_block_id("fragment", "trajectory_ode", "quadratic_drag_planar"): _join_lines([
        "    if use_drag && speed > 1e-8",
        "        drag = 0.5 * rho * Cd * A * speed^2;",
        "        drag_x = drag * vx(k-1) / speed;",
        "        drag_y = drag * vy(k-1) / speed;",
        "    else",
        "        drag_x = 0;",
        "        drag_y = 0;",
        "    end",
    ]),
    _family_block_id("fragment", "trajectory_ode", "gravity_planar"): "    gravity_y = g * use_gravity;",
    _family_block_id("fragment", "powered_ascent", "mass_depletion"): _join_lines([
        "    if use_mass_depletion",
        "        burned = min(fuel_mass, burn_rate * t(k-1));",
        "        current_mass = max(mass0 - burned, mass0 - fuel_mass);",
        "    else",
        "        current_mass = mass0;",
        "    end",
    ]),
    _family_block_id("fragment", "powered_ascent", "pitch_program"): _join_lines([
        "    if use_pitch_program",
        "        pitch_ratio = min(max(t(k-1) / max(pitch_ramp_time, dt), 0), 1);",
        "        gamma_cmd = deg2rad(pitch_start_deg + (pitch_end_deg - pitch_start_deg) * pitch_ratio);",
        "    else",
        "        gamma_cmd = atan2(vy(k-1), max(vx(k-1), 1e-9));",
        "    end",
    ]),
    _family_block_id("fragment", "powered_ascent", "constant_thrust_vector"): _join_lines([
        "    if use_thrust",
        "        thrust_vec = thrust * [cos(gamma_cmd); sin(gamma_cmd)];",
        "    else",
        "        thrust_vec = [0; 0];",
        "    end",
    ]),
    _family_block_id("fragment", "powered_ascent", "quadratic_drag_planar"): _join_lines([
        "    if use_drag",
        "        drag_mag = 0.5 * rho * Cd * A * speed^2;",
        "        drag_vec = drag_mag * [vx(k-1); vy(k-1)] / speed;",
        "    else",
        "        drag_vec = [0; 0];",
        "    end",
    ]),
    _family_block_id("fragment", "powered_ascent", "gravity_planar"): _join_lines([
        "    if use_gravity",
        "        gravity_vec = [0; -current_mass * g];",
        "    else",
        "        gravity_vec = [0; 0];",
        "    end",
    ]),
    _family_block_id("fragment", "reentry_dynamics", "atmosphere_density_decay"): _join_lines([
        "    if use_atmosphere",
        "        rho_local = air_density_ref * exp(-max(y(k-1), 0) / max(scale_height, 1e-9));",
        "    else",
        "        rho_local = air_density_ref;",
        "    end",
    ]),
    _family_block_id("fragment", "reentry_dynamics", "gravity_planar"): _join_lines([
        "    if use_gravity",
        "        gravity_vec = [0; -mass0 * g];",
        "    else",
        "        gravity_vec = [0; 0];",
        "    end",
    ]),
    _family_block_id("fragment", "reentry_dynamics", "quadratic_drag_planar"): _join_lines([
        "    if use_drag",
        "        drag_mag = 0.5 * rho_local * Cd * A * speed^2;",
        "        drag_vec = drag_mag * [vx(k-1); vy(k-1)] / speed;",
        "    else",
        "        drag_mag = 0;",
        "        drag_vec = [0; 0];",
        "    end",
    ]),
    _family_block_id("fragment", "reentry_dynamics", "lift_to_drag_planar"): _join_lines([
        "    if use_lift && speed > 1e-8",
        "        lift_mag = drag_mag * lift_to_drag;",
        "        lift_dir = [-vy(k-1); vx(k-1)] / speed;",
        "        lift_vec = lift_mag * lift_dir;",
        "    else",
        "        lift_vec = [0; 0];",
        "    end",
    ]),
    _family_block_id("fragment", "reentry_dynamics", "heating_rate_proxy"): _join_lines([
        "    if use_heating",
        "        q_dot = 1.83e-4 * sqrt(max(rho_local, 1e-9)) * speed^3;",
        "    else",
        "        q_dot = 0;",
        "    end",
    ]),
    _family_block_id("fragment", "aircraft_point_mass", "thrust_drag_balance"): _join_lines([
        "    rho_local = air_density * exp(-max(y(k-1), 0) / 8500);",
        "    drag = 0.5 * rho_local * Cd * A * v(k-1)^2;",
        "    if use_force_balance",
        "        current_thrust = thrust;",
        "    else",
        "        current_thrust = drag;",
        "    end",
    ]),
    _family_block_id("fragment", "aircraft_point_mass", "lift_balance"): _join_lines([
        "    if use_lift",
        "        lift = 0.5 * rho_local * lift_coeff * wing_area * v(k-1)^2;",
        "    else",
        "        lift = mass * g * cos(gamma(k-1));",
        "    end",
    ]),
    _family_block_id("fragment", "aircraft_point_mass", "bank_turn_rate"): _join_lines([
        "    if use_bank",
        "        heading_rate = g * tand(bank_angle_deg) / max(v(k-1), 1e-6);",
        "    else",
        "        heading_rate = 0;",
        "    end",
    ]),
    _family_block_id("fragment", "interceptor_guidance", "constant_speed_target"): _join_lines([
        "    if use_target_motion",
        "        target_heading = deg2rad(target_heading_deg);",
        "        target_vel = target_speed * [cos(target_heading); sin(target_heading)];",
        "    else",
        "        target_vel = [0; 0];",
        "    end",
    ]),
    _family_block_id("fragment", "interceptor_guidance", "closing_velocity"): _join_lines([
        "    rel = [target_x(k-1) - missile_x(k-1); target_y(k-1) - missile_y(k-1)];",
        "    range_now = max(norm(rel), 1e-6);",
        "    los = atan2(rel(2), rel(1));",
        "    if use_closing_velocity",
        "        los_rate = (los - prev_los) / dt;",
        "        closing_speed = missile_speed - dot(target_vel, rel / range_now);",
        "    else",
        "        los_rate = 0;",
        "        closing_speed = missile_speed;",
        "    end",
    ]),
    _family_block_id("fragment", "interceptor_guidance", "proportional_navigation"): _join_lines([
        "    if use_guidance",
        "        missile_heading_cmd = missile_heading(k-1) + nav_gain * los_rate * dt;",
        "    else",
        "        missile_heading_cmd = los;",
        "    end",
    ]),
    _family_block_id("update", "launch_dynamics", "state"): _join_lines([
        "    a(k) = (current_thrust - drag - weight) / max(m(k), 1e-9);",
        "    if k > 1",
        "        v(k) = v(k-1) + a(k) * dt;",
        "        h(k) = max(0, h(k-1) + v(k) * dt);",
        "    end",
    ]),
    _family_block_id("update", "trajectory_ode", "state"): _join_lines([
        "    ax(k) = (thrust_x - drag_x) / max(mass0, 1e-9);",
        "    ay(k) = (thrust_y - drag_y) / max(mass0, 1e-9) - gravity_y;",
        "    vx(k) = vx(k-1) + ax(k) * dt;",
        "    vy(k) = vy(k-1) + ay(k) * dt;",
        "    x(k) = x(k-1) + vx(k) * dt;",
        "    y(k) = max(0, y(k-1) + vy(k) * dt);",
        "    if k > 5 && y(k) <= 0 && vy(k) < 0",
        "        x(k+1:end) = x(k);",
        "        y(k+1:end) = 0;",
        "        vx(k+1:end) = vx(k);",
        "        vy(k+1:end) = 0;",
        "        break;",
        "    end",
    ]),
    _family_block_id("update", "powered_ascent", "state"): _join_lines([
        "    net_force = thrust_vec - drag_vec + gravity_vec;",
        "    ax = net_force(1) / max(current_mass, 1e-9);",
        "    ay = net_force(2) / max(current_mass, 1e-9);",
        "    vx(k) = vx(k-1) + ax * dt;",
        "    vy(k) = vy(k-1) + ay * dt;",
        "    x(k) = x(k-1) + vx(k) * dt;",
        "    y(k) = max(0, y(k-1) + vy(k) * dt);",
        "    mass(k) = current_mass;",
        "    flight_path_deg(k) = rad2deg(atan2(vy(k), max(vx(k), 1e-9)));",
    ]),
    _family_block_id("update", "reentry_dynamics", "state"): _join_lines([
        "    net_force = lift_vec - drag_vec + gravity_vec;",
        "    ax = net_force(1) / max(mass0, 1e-9);",
        "    ay = net_force(2) / max(mass0, 1e-9);",
        "    vx(k) = vx(k-1) + ax * dt;",
        "    vy(k) = vy(k-1) + ay * dt;",
        "    x(k) = x(k-1) + vx(k) * dt;",
        "    y(k) = max(0, y(k-1) + vy(k) * dt);",
        "    heat_load(k) = heat_load(k-1) + q_dot * dt;",
        "    if k > 5 && y(k) <= 0",
        "        x(k+1:end) = x(k);",
        "        y(k+1:end) = 0;",
        "        vx(k+1:end) = vx(k);",
        "        vy(k+1:end) = vy(k);",
        "        heat_load(k+1:end) = heat_load(k);",
        "        break;",
        "    end",
    ]),
    _family_block_id("update", "aircraft_point_mass", "state"): _join_lines([
        "    v_safe = max(v(k-1), 1e-6);",
        "    v_dot = (current_thrust - drag) / max(mass, 1e-9) - g * sin(gamma(k-1));",
        "    gamma_dot = lift / (max(mass, 1e-9) * v_safe) - g * cos(gamma(k-1)) / v_safe;",
        "    v(k) = max(1e-3, v(k-1) + v_dot * dt);",
        "    gamma(k) = gamma(k-1) + gamma_dot * dt;",
        "    heading(k) = heading(k-1) + heading_rate * dt;",
        "    x(k) = x(k-1) + v(k) * cos(gamma(k)) * cos(heading(k)) * dt;",
        "    y(k) = max(0, y(k-1) + v(k) * sin(gamma(k)) * dt);",
    ]),
    _family_block_id("update", "interceptor_guidance", "state"): _join_lines([
        "    missile_heading(k) = missile_heading_cmd;",
        "    target_x(k) = target_x(k-1) + target_vel(1) * dt;",
        "    target_y(k) = target_y(k-1) + target_vel(2) * dt;",
        "    missile_x(k) = missile_x(k-1) + missile_speed * cos(missile_heading(k)) * dt;",
        "    missile_y(k) = missile_y(k-1) + missile_speed * sin(missile_heading(k)) * dt;",
        "    miss_distance(k) = hypot(target_x(k) - missile_x(k), target_y(k) - missile_y(k));",
        "    prev_los = los;",
    ]),
    _family_block_id("postprocess", "launch_dynamics", "metrics"): _join_lines([
        "[max_h, idx] = max(h);",
        "fprintf('Max altitude: %.2f m at t = %.2f s\\n', max_h, t(idx));",
        "fprintf('Final velocity: %.2f m/s\\n', v(end));",
    ]),
    _family_block_id("postprocess", "powered_ascent", "metrics"): _join_lines([
        "[max_alt, idx] = max(y);",
        "fprintf('Peak altitude: %.2f m at t = %.2f s\\n', max_alt, t(idx));",
        "fprintf('Final mass: %.2f kg\\n', mass(end));",
    ]),
    _family_block_id("postprocess", "reentry_dynamics", "metrics"): _join_lines([
        "fprintf('Peak heat load proxy: %.2f\\n', max(heat_load));",
        "fprintf('Touchdown range: %.2f km\\n', x(end) / 1e3);",
    ]),
    _family_block_id("postprocess", "aircraft_point_mass", "metrics"): _join_lines([
        "fprintf('Cruise distance: %.2f km\\n', x(end) / 1e3);",
        "fprintf('Final altitude: %.2f m\\n', y(end));",
    ]),
    _family_block_id("postprocess", "interceptor_guidance", "metrics"): _join_lines([
        "[min_miss, idx] = min(miss_distance);",
        "fprintf('Minimum miss distance: %.2f m at t = %.2f s\\n', min_miss, t(idx));",
    ]),
    _family_block_id("output", "launch_dynamics", "plots"): _join_lines([
        "figure('Name', 'Launch Dynamics 1D');",
        "subplot(3,1,1); plot(t, h, 'LineWidth', 1.6); grid on; ylabel('Altitude (m)'); title('IR-Block Launch Dynamics');",
        "subplot(3,1,2); plot(t, v, 'LineWidth', 1.6); grid on; ylabel('Velocity (m/s)');",
        "subplot(3,1,3); plot(t, a, 'LineWidth', 1.6); grid on; ylabel('Acceleration (m/s^2)'); xlabel('Time (s)');",
    ]),
    _family_block_id("output", "trajectory_ode", "plots"): _join_lines([
        "figure('Name', 'Trajectory Dynamics 2D');",
        "subplot(2,2,1); plot(x, y, 'LineWidth', 1.8); grid on; xlabel('X (m)'); ylabel('Y (m)'); title('IR-Block Trajectory');",
        "subplot(2,2,2); plot(t, vx, 'LineWidth', 1.5); hold on; plot(t, vy, 'LineWidth', 1.5); grid on; legend('v_x', 'v_y'); xlabel('Time (s)'); ylabel('Velocity (m/s)');",
        "subplot(2,2,3); plot(t, hypot(vx, vy), 'LineWidth', 1.5); grid on; xlabel('Time (s)'); ylabel('Speed (m/s)');",
        "subplot(2,2,4); plot(t, ax, 'LineWidth', 1.5); hold on; plot(t, ay, 'LineWidth', 1.5); grid on; legend('a_x', 'a_y'); xlabel('Time (s)'); ylabel('Acceleration (m/s^2)');",
    ]),
    _family_block_id("output", "powered_ascent", "plots"): _join_lines([
        "figure('Name', 'Powered Ascent');",
        "subplot(2,2,1); plot(x / 1e3, y / 1e3, 'LineWidth', 1.8); grid on; xlabel('Downrange (km)'); ylabel('Altitude (km)'); title('Powered Ascent Trajectory');",
        "subplot(2,2,2); plot(t, hypot(vx, vy), 'LineWidth', 1.6); grid on; xlabel('Time (s)'); ylabel('Speed (m/s)');",
        "subplot(2,2,3); plot(t, mass, 'LineWidth', 1.6); grid on; xlabel('Time (s)'); ylabel('Mass (kg)');",
        "subplot(2,2,4); plot(t, flight_path_deg, 'LineWidth', 1.6); grid on; xlabel('Time (s)'); ylabel('Flight Path (deg)');",
    ]),
    _family_block_id("output", "reentry_dynamics", "plots"): _join_lines([
        "figure('Name', 'Reentry Dynamics');",
        "subplot(2,2,1); plot(x / 1e3, y / 1e3, 'LineWidth', 1.8); grid on; xlabel('Range (km)'); ylabel('Altitude (km)'); title('Reentry Trajectory');",
        "subplot(2,2,2); plot(t, hypot(vx, vy), 'LineWidth', 1.6); grid on; xlabel('Time (s)'); ylabel('Speed (m/s)');",
        "subplot(2,2,3); plot(t, heat_load, 'LineWidth', 1.6); grid on; xlabel('Time (s)'); ylabel('Heat Load Proxy');",
        "subplot(2,2,4); plot(t, y / 1e3, 'LineWidth', 1.6); grid on; xlabel('Time (s)'); ylabel('Altitude (km)');",
    ]),
    _family_block_id("output", "aircraft_point_mass", "plots"): _join_lines([
        "figure('Name', 'Aircraft Point Mass');",
        "subplot(2,2,1); plot(x / 1e3, y, 'LineWidth', 1.8); grid on; xlabel('Range (km)'); ylabel('Altitude (m)'); title('Aircraft Trajectory');",
        "subplot(2,2,2); plot(t, v, 'LineWidth', 1.6); grid on; xlabel('Time (s)'); ylabel('Speed (m/s)');",
        "subplot(2,2,3); plot(t, rad2deg(gamma), 'LineWidth', 1.6); grid on; xlabel('Time (s)'); ylabel('Flight Path (deg)');",
        "subplot(2,2,4); plot(t, rad2deg(heading), 'LineWidth', 1.6); grid on; xlabel('Time (s)'); ylabel('Heading (deg)');",
    ]),
    _family_block_id("output", "interceptor_guidance", "plots"): _join_lines([
        "figure('Name', 'Interceptor Guidance');",
        "subplot(1,2,1); plot(target_x, target_y, 'r-', 'LineWidth', 1.8); hold on; plot(missile_x, missile_y, 'b--', 'LineWidth', 1.8); grid on; axis equal; xlabel('X (m)'); ylabel('Y (m)'); title('Intercept Geometry'); legend('Target', 'Interceptor');",
        "subplot(1,2,2); plot(t, miss_distance, 'LineWidth', 1.8); grid on; xlabel('Time (s)'); ylabel('Miss Distance (m)'); title('Miss Distance Evolution');",
    ]),
}

for block_id, text in STATIC_BLOCKS.items():
    _register_text_block(BLOCK_LIBRARY, block_id, text)
